### ISSUE TITLE
ajouts à faire

### ISSUE THREAD

**Issue by kael79** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#1]
cases à cocher :
- expérience de compétence
- blessure grave / inconscient / mourant
- folie passagère / permanante

**Comment by kael79** [comment]
Pour traductions :
Ajouter dossier lang et y intégrer les labels afin de ne plus avoir les noms en dur dans le code principale.

**Comment by kael79** [comment]
Possibilité de dépenser de la chance pour améliorer son degré de réussite (ex : pour transformer un succès normal en succès majeur ou extrème).

**Comment by HavlockV** [comment]
Tout est implémenté.
