### ISSUE TITLE
[Feature request] It would be awesome to be able to drag-n-drop weapon item

### ISSUE THREAD

**Issue by huttyman** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#102]
Hi, Thanks for great work. It look really amazing. I dont know if this is the right place for ask for more option.  

Can you make weapon item able to drag-n-drop to macro bar and also able to drag to weapon compendium?  It would be alot faster for player to click on macro bar(and skill too for example dodge). Thx.

**Comment by HavlockV** [comment]
Thanks for the suggestion. I'll leave this open as a reminder and try to have a look at it.
