### ISSUE TITLE
[Feature Request] Implement actor template for monsters/entities

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#103]
Templates specifically for Mythos Creatures/Monsters/Entities that can have a Sanity Loss field for viewing them.

**Comment by HavlockV** [comment]
Thanks for the report. The field is on the template already and will be available shortly on the sheets, including a button to push to trigger automatically the SAN and SAN loss rolls. SAN management will be the next focus, after damage and missing sheets (items, vehicules)

**Comment by HavlockV** [comment]
SAN field added in 0.3.2
To roll a SAN check make as many PC's token active target and click on the SAN loss label on a monster sheet. This will trigger a chat card for every target and allow players to roll. Holding shift while clicking will fast forward the check.
