### ISSUE TITLE
[Feature Request] Implement Pulp Talents & Archetypes and Professions

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#104]
Could we have item templates for pulp talents&archetypes and professions? Also a place in the character sheet to store pulp talents depending on the pulp level (low pulp, medium pulp, high pulp). Profession templates could also list point calculations (EDUx2 +APP x2 for instance). Maybe down the road this can be used for character creation automation?

**Comment by HavlockV** [comment]
Thank for the suggestion, appreciated.
I am not very familiar with pulp rules, someone is having a look at it right now.
The system seems to be usable as it is for pulp providing you disable the auto HP calculation.
I will have a look at the others sheet (talents, archetype and professions). At this point automation of character creation isn't a priority (lots of basic stuff still need some work), but it's on the plan.

**Comment by Vass1979** [comment]
If I can help with any part of the pulp rules, let me know. I've used Pulp Rules for my games for 2 years now, know them inside out :)

I wish I could be more help to this project. I thought I could learn some javascript and start making actual contributions instead of whining and requesting all the time, but I was trying to make sense of the smallest of things (editing the character sheet) and my head exploded! I'll keep trying though!

**Comment by Vass1979** [comment]
Would it be easier instead of the whole request here to just get a field to write down the Pulp Arhetype in the character sheet and an area to write the pulp talents? And that way you could take your time with a full blown integration of the whole thing :)
