### ISSUE TITLE
[Feature Request] Tag on skill sheet to indicate Era of Play

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#107]
Some skills only come into play on specific era's, for instance computers would only be applicable in modern. It would be nice to have a tag to differentiate between skills for different era's. (1920's, Modern, Invictus, Down Darker Trails, Dark Ages)

**Comment by HavlockV** [comment]
Thanks for the suggestion.
That's actually a point that was discussed at the very beginning and wasn't really solved.
In the early version there were tag(s) for each skill. This created some confusion and wasn't used.
It was ruled to remove the tags and create different PC sheets for different eras. In the mean time it was possible to create skills 'on the fly (directly from the sheet)' or by drag and drop (lot's of keepers love to have skills with crazy names for their villains or PCs like 'be a pain 80%' or 'hate the PC 75%'.
I'm working on a new skill system and sheets that I hope will be more practical. The tag may come back at that time.
