### ISSUE TITLE
Unknown difficulty label

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#110]
Is this intentional?

![screenshot 142](https://user-images.githubusercontent.com/16079668/91755037-c3419e00-ebca-11ea-9769-4f196b5661e9.jpg)

I am not sure if ????? is a localization problem and in english it is shown "Blind roll", or "Unknown"

**Comment by HavlockV** [comment]
It was hard coded on madter then localzed on develop.
It will be fully localized on master after the next merge.

**Comment by lozalojo** [comment]
Ok, HavlockV!

Thank you for your work; module is progressing, step by step. I'd just wish I now js/css to help you with this project, but unfortunately, i dont.

My two cents: I've just pushed an update to the spanish translation file.
