### ISSUE TITLE
[Feature request] Roll on atributes

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#111]
Make attributes rollable (roll for DEX, STR, CON...).

**Comment by Vass1979** [comment]
Am I missing something? They already are rollable

**Comment by lozalojo** [comment]
Really? I click on the number itself and nothing happens, so, it is me?

**Comment by lozalojo** [comment]
Ok, I was trying the number, not the label, the label brings in the roll menu.

Sorry!
