### ISSUE TITLE
Flow of the Fist Fights 

### ISSUE THREAD

**Issue by AdmiralNyar** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#112]
Hello HavlockV.

I'd like to propose better flow of opposed roll in close combat.

Now in the CoC7-FoundryVTT, the attacker decides on the target first,
then the attacker rolls, **then the defender see the roll results** and **decides on the response**
(dodge, fightback or maneuver), and finally the defender rolls.

In the rule book("Combat Flow Chart", page 109), the attacker decides on the
target first, then the defender decides on the response(dodge, fightback or maneuver),
 and finally **both sides roll at the same time**.

And if possible, it would be better if the defender's response option included "do nothing" :)

**Comment by HavlockV** [comment]
Thanks for the suggestion. That's indeed a very valid point of rule that I ignored. I'll have a look at it ASAP.

**Comment by HavlockV** [comment]
Corrected on 0.3.4 : If the initiator is the GM the PC can't see the attacker outcome until he decide to retaliate and rolls.
Keeper can still see everything.
The 'do nothing' will be added shortly
