### ISSUE TITLE
Update to new version of PDFoundry

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#113]
New version of PDFoundry has support for form fillable pdf's which would be great for character sheets

**Comment by HavlockV** [comment]
I was just having a look at It. It seems that the new version (0.7.x+) doesn't requires system integration anymore.
I'll dig further an if it's working without it I'll remove the system integration.

**Comment by HavlockV** [comment]
This is to confirm that the new version of PDFoundry doesn't require module integration anymore.
All previous PDF items are now journal entries. All PDF items will be converted to journal entries automatically on first launch.
Module integration with PDFoundry has been removed.
