### ISSUE TITLE
[Bug] Skills not translated

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#118]
Seems that something got broken in the translation system, all gets translated except skills:

CoC7th 0.3.2, no modules loaded, language set to spanish:

https://i.ibb.co/tLMfN89/screenshot-47.jpg

**Comment by DavidCMeier** [comment]
Nop, thats is ok. The Skills is in the database and normally you need to be safe with that because you can't use texts with rights.

**Comment by lozalojo** [comment]
This must be something HavlockV has changed in the code, when I first translated the module to spanish, I translated all the core skills, and I used the character sheet fully in spanish.

**Comment by lozalojo** [comment]
Ok, I translated using babele, skills are compendiums, sorry!
