### ISSUE TITLE
[Suggestion] Beautify/Fix the character sheet

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#122]
Currently it looks very plain (which I understand, there are other priorities right now) and at times confusing for players though.

* Occupation, residence, birthplace fields are very small
* Characteristic fields expand when you stretch the sheet, making it look funny
* Weird positioning for hard/extreme values making it confusing to read. (Added a screenshot for that)
![skill](https://user-images.githubusercontent.com/470640/92281839-67418700-eef4-11ea-81ec-01701ab86067.png)

* No hard/extreme values displayed for skills
*Right now if you have a big description in a skill's description field and you press to view details in the character sheet, it will present it inline on the skill list distorting the skill list. I think a better presentation would be triggering a popup of the actual skill item.

--PULP RELATED STUFF--

* Add a space for Archetype
* Add area for pulp talents
* Have a toggle in rules settings for pulp HP to autocalculate using pulp. (I know you can do this now manually, but I this way is more clean

I know it feels like I am whining, I 'm really not! A really appreciate what you have done here and I could not have done 1 1000th of it myself! Just providing some well intended feedback!

**Comment by HavlockV** [comment]
It's on the short term plan (after finishing the combat flows i.e. application of damage and maneuver)
