### ISSUE TITLE
[Bug Report] - Creature Token HP/San display

### ISSUE THREAD

**Issue by PhilMC157** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#126]
Hi HavlockV, i only signd up on GitHub in order contribute to the great work you are doing with the CoC Foundry System!
I just got into CoC and i was really happy to see, that someone is working on a proper FVTT system for it. 
Thank you for that, because i have zero programming skills.

**my specs:** 
macbook pro, FVTT 0.6.6, CoC 0.3.3
**Issue:**
 the **creature** token display bars for HP and Luck don't work correctly (see attached screenshot). The token for the Characters is working though.
![CoC_FVTT_MonsterSheet](https://user-images.githubusercontent.com/70864790/92337530-3b8ee000-f05f-11ea-9567-d28169734871.jpg)

**Comment by HavlockV** [comment]
Bars now should appear correctly for creatures and NPC in 0.3.4
Thank (again) for your feedback.
I leave this for you to close when tested.

**Comment by PhilMC157** [comment]
It's working now. Thank you very much.
