### ISSUE TITLE
[Suggestion] - Spell Section for Creatures/Monsters & Pop out for Weapon descriptions

### ISSUE THREAD

**Issue by PhilMC157** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#127]
Hi HavlockV,
**Spell Section for Creatures**
as an idea, would it be possible to add the Spell Section you have for Characters, to Creatures/Monsters as well?
Right now i'm adding them into the "notes" section.

**Pop out for Weapon/Attack descriptions**
taking the Ghoul as an example creature. it has a "bite and hold (mnvr)", which i put into its combat section.
To see the description of the actual maneuver i have to either click and look at the chat or i have to unlock the sheet and click the edit and the description button.
Would it be possible to have a dice and an info icon next to the attack names? 
dice = roll to attack, info = open attack sheet (deadly claws, bite and hold and so on...)
![CoC_FVTT_AttackDescription](https://user-images.githubusercontent.com/70864790/92338026-56af1f00-f062-11ea-887b-0f73f5bc0d72.jpg)
And again thanks for the awesome work you are doing!
- Philip

**Comment by HavlockV** [comment]
Thanks for your feedback, always appreciated.
The inventory has been updated and NPC/Cretures now supports Book, spells ans items in 0.3.4.
The maneuver is on the table, popup and/or display in the chat on successful hit.
This will be available ASAP.

**Comment by PhilMC157** [comment]
Sir, that was fast! :-)
I knew about the display of the maneuvers/weapon description in the chat window, but i found, while DMing the game, i felt i had to click 1 or 2 buttons too many. Especially in a fight situation i needed to look up the decription of the manouver attack really quick, but i had to "leave" the creature sheet to go to the chat window and click there again. I really like how u set up the attack in the chat window by the way! 
Hopefully i didn't misread your statement and u might be working on it already.
It was just idea to make the design and the access of information a little bit more intuative, quicker and in line with other sheets in other game system (DND 5e). 
Dice Symbol = roll for skill
Info Symbol = show pop of item

**Comment by PhilMC157** [comment]
Thanks again for all your work
