### ISSUE TITLE
[BUG] Creature sheet is missing POW field

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#134]
Not sure if you intended to remove EDU from creature and removed POW instead?

**Comment by HavlockV** [comment]
Shouldn't be. Creatures have all the same characteristic as PC/NPC.
If a characteristic is empty (no value and no formula) it will not be displayed on the creature sheet when it's locked.
Everything will be displayed when you unlock the creature sheet.
Click the small lock on the sheet to lock/unlock it.
If this doesn't work please post a screenshot of the sheet.

**Comment by Vass1979** [comment]
Yep, you are right!

So why is it that only POW gets hidden when it's zero?

**Comment by HavlockV** [comment]
Creature locked : 
![image](https://user-images.githubusercontent.com/65915923/92421212-b8ad7880-f177-11ea-8fa3-9c4887b1afae.png)
Creature unlocked, toggle the sheet to show formulas :
![image](https://user-images.githubusercontent.com/65915923/92421218-c2cf7700-f177-11ea-8c9d-8aa33b2656ca.png)
Entering a formula for POW and toggle the sheet back in values mode :
![image](https://user-images.githubusercontent.com/65915923/92421339-5dc85100-f178-11ea-84cf-1843f491e1e2.png)
Click on average (calculate all characteristic with averaged value from formula if present) or randomize
![image](https://user-images.githubusercontent.com/65915923/92421265-04f8b880-f178-11ea-9ce2-6d278cec3d52.png)
Once the sheet is locked POW value will be displayer :
![image](https://user-images.githubusercontent.com/65915923/92421292-235eb400-f178-11ea-9f6f-ad34c90f206d.png)

**Comment by Vass1979** [comment]
That makes much more sense, sorry for being stupid! Close this not-a-bug report :P

**Comment by HavlockV** [comment]
> That makes much more sense, sorry for being stupid! Close this not-a-bug report :P

There are no stupid questions, only stupids answers ;)
I know a wiki would be nice, it's somewhere down on the TODO list....

**Comment by Vass1979** [comment]
> > That makes much more sense, sorry for being stupid! Close this not-a-bug report :P
> 
> There are no stupid questions, only stupids answers ;)
> I know a wiki would be nice, it's somewhere down on the TODO list....

Hmm, a wiki is something I can actually help with! :D

**Comment by HavlockV** [comment]
I have a very busy shift this week but you proposal to help with the wiki didn't fall on deaf ears ;)
I'll try to get in touch probably next week IRL permitting.
