### ISSUE TITLE
[Feature Request] Add checkbox for profession skills

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#136]
Add to the character sheet a checkbox to mark profession skills.
Add a field that shows the number of points used in total in profession skills and other skills.

Maybe show those fields and checks when editing a character sheet?
This helps a lot creating characters.

**Comment by Vass1979** [comment]
I think there is a thought down the line to create some sort of character creation automation, but it's not a priority right now.

I think Havlock want's to implement all the core stuff first and then move to these aspects of the ruleset

**Comment by lozalojo** [comment]
He told that he is about to finish the combat flow and after that he plans taking a look at the character sheet, thats why I posted this feature request.

**Comment by Vass1979** [comment]
Yep, that's fair. Just saying :)

**Comment by HavlockV** [comment]
Yes there's a plan to do char generation down the road. I can have a look at that when I'll do a pass on the character sheet.

**Comment by HavlockV** [comment]
Implemented on 0.3.8
