### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#14]
The string 

"CoC7.Name": "Nombre",

does not get translated, maybe the id is not correct?

![image](https://user-images.githubusercontent.com/16079668/84406731-3958e900-ac0a-11ea-8a6c-260751ca9a90.png)

**Comment by HavlockV** [comment]
Hi lozalojo. Yes, we will have a pass on it.
Saw your translation, great work, I'll pass it on the next release.
Please be aware that localisation is still a work in progress, as I first developed everything quick, dirty and in English, and will need some tuning/modifications. Big part is still not 'localisable'.

Thanks for your feedback, I'll keep this open until fixed.

**Comment by lozalojo** [comment]
Great! Thank you for your work, I think there is a missing skill in the compendium, Engineering, maybe?

**Comment by kael79** [comment]
Hi lozalojo. For the Name, it will be corrected in my next push! :)
Thanks for your return !
