### ISSUE TITLE
[Feature] Add max luck field

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#141]
I know max luck is 99, but in order to make use of the token bars, that requires current luck/max luck - current hp/max hp - currenty san/max san.

Currently if you set one of the bars to show luck, the bar is always empty since there is no max luck field.

**Comment by lozalojo** [comment]
Just to clarify:

I set up hp and luck to show on hover, no max luck:
![](https://i.ibb.co/hsTSB7J/screenshot-177.jpg)

And the lower bar is shown as empty since there is no max luck:
![](https://i.ibb.co/VL0vpcV/screenshot-178.jpg)

**Comment by HavlockV** [comment]
Hidden field with max luck at 99 added, token can display a bar  attribs.lck with a max at 99
