### ISSUE TITLE
[Issues] Combat system

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#142]
HavlockV, I've been testing the combat systems and looks great! gratz!

Issues I've found so far:

1. When I make an attack, it always check "Fast", as if the target has moved more than 8 yrds.

2. When using "Multi. Shots", for example shooting 3 times with a .38, I add 3 shoots to the chat, and then it shows:
Bullets fired: 3/8, Shots fired: 3/3
But when I click fire, it leaves the gun empty, no more ammo, 0 bullets.
It happens also when I click on Multi.Shots and only configure one shot.

3. Another issue related with 2: I'd add automatically all shots (max of the weapon) when clicking the skill to fire; that is, when clicking Mult.Shots, then:
shots to add = min(remaining_bullets, max_shots_of_the_weapon)

**Comment by GabrielConnor** [comment]
Also, to add to this. Small target is selected even though the target has a build of 7 which would qualify me for a bonus die. And also target is 18.3 yards away yet extreme range is added instead of hard. My weapon has a 15 yard range.

![bug](https://user-images.githubusercontent.com/470640/93475614-bb833880-f8f0-11ea-9b1c-918543de8db3.jpg)

**Comment by HavlockV** [comment]
Thanks for the feedback.
>     1. When I make an attack, it always check "Fast", as if the target has moved more than 8 yrds.
fast is by default selected if the target MOV is 8 or more. Could you confirm the movement value of your target.

>     2. When using "Multi. Shots", for example shooting 3 times with a .38, I add 3 shoots to the chat, and then it shows:
>        Bullets fired: 3/8, Shots fired: 3/3
>        But when I click fire, it leaves the gun empty, no more ammo, 0 bullets.
>        It happens also when I click on Multi.Shots and only configure one shot.
That's a bug, identified and corrected. I'll push the correction on develop now then on master probably tomorrow.

>     3. Another issue related with 2: I'd add automatically all shots (max of the weapon) when clicking the skill to fire; that is, when clicking Mult.Shots, then:
>        shots to add = min(remaining_bullets, max_shots_of_the_weapon)
I didn't get that last point, could you please clarify it.

**Comment by Vass1979** [comment]
> Thanks for the feedback.
> 
> > ```
> > 1. When I make an attack, it always check "Fast", as if the target has moved more than 8 yrds.
> > ```
> 
> fast is by default selected if the target MOV is 8 or more. Could you confirm the movement value of your target.
> 
>

I think the rule applies if you are shooting a moving target that has a MOV of 8 or greater. I would assume if the target is stationary, you don't get the penalty die because of it's high speed.

**Comment by lozalojo** [comment]
> fast is by default selected if the target MOV is 8 or more. Could you confirm the movement value of your target.

To apply the rule, the target must have moved more than 8 yrds that turn, not only having MOV 8+ applies. So in most circumstances, that rule does not apply. So I wouldnt make it default just for having MOV 8+.

[Feature] I'd also add the "Take cover" modifier as a new clickeable option, when someone is shot, he can choose to take cover making a dodge roll, if success, then +1P to the attacker.

> I didn't get that last point, could you please clarify it.

When I click the Multi. Shots button it shows the following menu:

![](https://i.ibb.co/YWYgLTq/screenshot-174.jpg)

Then I have to click manually "Shoot Profundo Armas de fuego (Arma corta)..." three times to shot 3 bullets:

[Fix] Shot, not shoot.

![](https://i.ibb.co/R61yy4K/screenshot-175.jpg)

And then I click on Fire to perform 3 individual shots with +1P.

What I say is that when I click "Mult. Shots", the "bullets" could be filled in automatically, up to the max of the capacity of the gun (3) and considering it has enough ammo, so I dont have to click three times in "Shoot Profundo Armas...".

99% of the times when multishoting, the user is going to shoot the maximum bullets he can, that's why I suggest autoentering the 3 bullets or whatever bullets the gun is able to do.

**Comment by Vass1979** [comment]
> [Feature] I'd also add the "Take cover" modifier as a new clickeable option, when someone is shot, he can choose to take cover making a dodge roll, if success, then +1P to the attacker.

That one is already there. Under Cover. Applies for both when the target is in cover or dives for cover

**Comment by lozalojo** [comment]
> That one is already there. Under Cover. Applies for both when the target is in cover or dives for cover

I have to check the rules, can you take cover if you are already under cover? Does the penalties stack? It does not make sense to me, so it might be ok to have one modifier for both circumstances.

**Comment by HavlockV** [comment]
> 
> 
> > That one is already there. Under Cover. Applies for both when the target is in cover or dives for cover
> 
> I have to check the rules, can you take cover if you are already under cover? Does the penalties stack? It does not make sense to me, so it might be ok to have one modifier for both circumstances.

You're actually right, this is two different things. Diving for cover grant 1 penalty die, request a dodge roll and forfeit all remaining attack and the defender fall prone. This cover is there for when you are under cover (more than 50%).
It can be used for the time being to simulate that dive for cover rule.
The plan was initially to have the exact mechanism you're describing, a popup on the target side asking for the roll and adding the penalty die for a successful dive.
That turns out to be kind of complex and I didn't do it on a first pass. It will be in the future.

**Comment by Vass1979** [comment]
It doesn't specify if the penalties stuck anywhere. My ruling would be they don't.

Imagine this: A player dives for cover behind some boxes. Did he dive for cover or conceal? Well, both, but I think the intent is for only 1 penalty die to the attacker as the situation from the attacker perspective would be that the player is behind cover.

**Comment by lozalojo** [comment]
> It doesn't specify if the penalties stuck anywhere. My ruling would be they don't.
> 
> Imagine this: A player dives for cover behind some boxes. Did he dive for cover or conceal? Well, both, but I think the intent is for only 1 penalty die to the attacker as the situation from the attacker perspective would be that the player is behind cover.

This is just pure ruling discussion, but I love the rules mechanisms of all games...

In the situation you describe: you are under cover (50%) and see that you are going to be shoted. You decide to fall prone diving for cover making a dodge roll. Shouldnt you benefice from a 100% cover since you are on the floor and the enemy does not see you at all?

To be honest, I dont know if those two modifiers should stack, I dont think there is a paragraph on the rules for this situation.

**Comment by HavlockV** [comment]
> 
> 
> > fast is by default selected if the target MOV is 8 or more. Could you confirm the movement value of your target.
> 
> To apply the rule, the target must have moved more than 8 yrds that turn, not only having MOV 8+ applies. So in most circumstances, that rule does not apply. So I wouldnt make it default just for having MOV 8+.

Yes I can easily change that default behavior, or add an option in the system.
Checking preceding move of a target is not easy with foundry.

> [Fix] Shot, not shoot.

Fixed, will be available on the next push.

> [...]
> 99% of the times when multishoting, the user is going to shoot the maximum bullets he can, that's why I suggest autoentering the 3 bullets or whatever bullets the gun is able to do.

Multi target allows to shoot on different targets. If you select 2+ target you can switch between then and take 1 shot at the first, 1 at the second....
What wan be done is that if only 1 target is selected to automatically shoot to the max capacity of the weapon.
Even so, you may want to shoot only 2 out of 3 bullets. I need to think about that...

**Comment by HavlockV** [comment]
> To be honest, I dont know if those two modifiers should stack, I dont think there is a paragraph on the rules for this situation.

Yes. CoC rules on many point are... open for discussion. I personally would stack both modifier. That's why everything on the card can be over ruled by the keeper, it's just a pre-fill.

**Comment by lozalojo** [comment]
> Multi target allows to shoot on different targets. If you select 2+ target you can switch between then and take 1 shot at the first, 1 at the second....

You are right, but how does it work?

Target enemy 1, click "Shoot Profundo Armas...". 
Target enemy 2, click "Shoot Profundo Armas...".
Target enemy 3, click "Shoot Profundo Armas...".

> What wan be done is that if only 1 target is selected to automatically shoot to the max capacity of the weapon.

Might be a solution.

**Comment by HavlockV** [comment]
It's actually implemented.
If you select 2+ target you'll see a target selector appearing just above the range selector. You can click on a target and it will change the tab with the range selection. Each tab is pre-filled with range and other options. If you're using auto-fire it will also calculate the transit bullets wasted switching targets. 
Don't have my computer with me until tomorrow, I'll make some screenshots then.

**Comment by lozalojo** [comment]
> It's actually implemented.
> If you select 2+ target you'll see a target selector appearing just above the range selector. You can click on a target and it will change the tab with the range selection. Each tab is pre-filled with range and other options. If you're using auto-fire it will also calculate the transit bullets wasted switching targets.
> Don't have my computer with me until tomorrow, I'll make some screenshots then.

Do not mind, I can check by myself, i'm just making a pulling request to your repository to update es.json file to the lastest 0.3.6 version.

I've pulled it to develop, last time I pulled it to master, sorry.

**Comment by lozalojo** [comment]
Checked, when you select several enemies, when performing multiple shots, it allows you to select the icon of the specific enemy you want to make a given attack. Great!
