### ISSUE TITLE
[Feature] Autocalc range values

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#143]
Range are always:
base
base*2
base*4

So I would autocalc range values.

Now when I set a weapon range to 15 and leave the other fields empty, those fields are set to zero and cause the combat assistant to tell the target is out of range.

**Comment by HavlockV** [comment]
Is that when you're using a shotgun type weapon ?

**Comment by lozalojo** [comment]
Nope, with a .38 gun, that's what i used for testing this morning.

Setting ranges to 15/30/60 solved the issue (no more out of range message), but since ranges are fixed values I wonder if it can be autocalculated, not to force to enter all the fields

**Comment by Vass1979** [comment]
You should not be getting more than one range fields unless you've checked the "shotgun" label on the weapon. Could you please post a screenshot of the weapon sheet you are using?

**Comment by lozalojo** [comment]
Yes, Shotgun is selected, it was another person the one that created those weapons, I will fix it. 

Thanks!

![](https://i.ibb.co/mX8Phhg/screenshot-176.jpg)
