### ISSUE TITLE
[BUG] Penalty Die Translation

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#146]
Translation should be Penalty Die instead of Malus Die

![malus](https://user-images.githubusercontent.com/470640/93487541-48cc8a00-f8fd-11ea-9e4e-7523de4d42fd.png)

**Comment by HavlockV** [comment]
Yes, malus is in frenglish that's why ;)
Corrected on develop will be on the next release. thanks for feedback.

**Comment by Vass1979** [comment]
Funnily enough, we have a "points" system for our driving insurance in Greece that is called Bonus/Malus. So that makes sense :)
