### ISSUE TITLE
Development Phase Feedback

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#155]
As it works right now in the development tab ,when it's time for the development phase your players click the development button, some rolls happen behind the scenes and if successful points get added.

Now the problem with this, at least I KNOW it is for my players, is that there is hardly any player feedback and the players don't get the satisfaction of seeing their rolls.

What I suggest instead is some sort of popup shows up that lists the skills that are eligible for improvement, with their existing value, then a roll button next to each skill. Then the player can roll for that skill, see the result in chat and if eligible roll the 1d10 via a different button on  popup to get the increase. Again, displaying that result in chat. I think this would make for a far better player experience!

Obviously, keep the existing system as an option for people who prefer it, not saying my proposed system is better, just a suggestion!

**Comment by lozalojo** [comment]
Impressive work!

I will post my impressions so far here:

[1] I agree with Gabriel, no automatic roll, but mark in yellow the skills you have to roll (as it currently is), then allow the player to roll, a message in chat (like combat) saying:

Rafael Nadal
Tennis Roll (235%) - development
Success
34
No gain

And If you fail, then:

"Failed", roll % gain, and the result to be added automatically to the "experience" column.

[2] Development to the right, I dont want my players to click "dev" to roll for their skills, the players when they get nervous they click everywhere, I dont want them to roll for development every time I request a roll.

I know this is in the route plan to redo the character sheet, but maybe the tabs to the right side would help legibility of the different tabs.

![](https://i.ibb.co/TcfD79q/unknown.png)

[3] In the header Personal points, occupation points, experience points, another fields to set the attributes and multipliers for occupation points.
Occ. attr 1:  EDU, Mult. 1: 2, Occ. attr. 2: DEX Mult. 2: 2

And then put those totals in the Personal points and Occupation points MAX values:
Occupation points: 230 (EDUx2+DEXx2) , Personal points: 134 (INT x2)

Occ. attr. 1 & 2 are dropdown to chose between attributes list, and Mult. 1 & 2 are numbers.

**Comment by Vass1979** [comment]
On your second point. Development phase could be something that is triggered/enabled by the keeper so the players don't accidentally hit it.

On your third point, I think Havlock plans to make Occupation Sheets (like skill sheets) and there you can fill in the specific occupation points, eg EDUx2 & APPx2. Then when you drop that occupation on the character sheet it will auto-fill the points field!

**Comment by lozalojo** [comment]
What I do not have a clear opinion is wether I prefer to have an independent tab for development and have skills and development tabs separately, or I prefer to have a single tab "skills" that turns to be the development tab when unlocking the padlock.

Honestly I dont know.

**Comment by HavlockV** [comment]
First of all, as always thanks for the feedback appreciated.

**Comment by HavlockV** [comment]
> As it works right now in the development tab ,when it's time for the development phase your players click the development button, some rolls happen behind the scenes and if successful points get added.

I will add a feedback in the chatlog
> Now the problem with this, at least I KNOW it is for my players, is that there is hardly any player feedback and the players don't get the satisfaction of seeing their rolls.

I can also hide the development tab when the sheet is locked, that will prevent some miss click
> What I suggest instead is some sort of popup shows up that lists the skills that are eligible for improvement, with their existing value, then a roll button next to each skill. Then the player can roll for that skill, see the result in chat and if eligible roll the 1d10 via a different button on popup to get the increase. Again, displaying that result in chat. I think this would make for a far better player experience!

I was thinking more about a chat-card than a popup, event on the chat are easier to handle. But yes I'll go that way. 
> Obviously, keep the existing system as an option for people who prefer it, not saying my proposed system is better, just a suggestion!

I was thinking to keep the button, pushing it will trigger the chat card. Pushing it with shift will fast forward everything.

**Comment by HavlockV** [comment]
> [1] I agree with Gabriel, no automatic roll, but mark in yellow the skills you have to roll (as it currently is), then allow the player to roll, a message in chat (like combat) saying:
> 
> Rafael Nadal
> Tennis Roll (235%) - development
> Success
> 34
> No gain
> 
> And If you fail, then:
> 
> "Failed", roll % gain, and the result to be added automatically to the "experience" column.

I won't comment on Nadal tennis, but I agree, some feedback of what is happening would be much better.
> [2] Development to the right, I dont want my players to click "dev" to roll for their skills, the players when they get nervous they click everywhere, I dont want them to roll for development every time I request a roll.
> 
> I know this is in the route plan to redo the character sheet, but maybe the tabs to the right side would help legibility of the different tabs.

Yes tabs to the right are 'prettier' something to consider, thanks for the idea.

> [3] In the header Personal points, occupation points, experience points, another fields to set the attributes and multipliers for occupation points.
> Occ. attr 1: EDU, Mult. 1: 2, Occ. attr. 2: DEX Mult. 2: 2
> 
> And then put those totals in the Personal points and Occupation points MAX values:
> Occupation points: 230 (EDUx2+DEXx2) , Personal points: 134 (INT x2)
> 
> Occ. attr. 1 & 2 are dropdown to chose between attributes list, and Mult. 1 & 2 are numbers.

That will come with the occupation/archetype sheets. Then you can just drag and drop them to get everything setup.

**Comment by lozalojo** [comment]
> I won't comment on Nadal tennis, but I agree, some feedback of what is happening would be much better.

Sorry, didnt mean to offend, I forgot you are french and maybe tired of Nadal at Roland Garros. Not my intention.

**Comment by Vass1979** [comment]
> > I won't comment on Nadal tennis, but I agree, some feedback of what is happening would be much better.
> 
> Sorry, didnt mean to offend, I forgot you are french and maybe tired of Nadal at Roland Garros. Not my intention.

Too late, we're all super offended now! I say BAN HIM Havlock! :P

**Comment by lozalojo** [comment]
> > > I won't comment on Nadal tennis, but I agree, some feedback of what is happening would be much better.
> > 
> > 
> > Sorry, didnt mean to offend, I forgot you are french and maybe tired of Nadal at Roland Garros. Not my intention.
> 
> Too late, we're all super offended now! I say BAN HIM Havlock! :P

But didnt you were Greek? I think i mixed things up.

**Comment by Vass1979** [comment]
I am Greek, just joking around :)

**Comment by HavlockV** [comment]
That was a pun also. I appreciate tennis, the nationality of the player is a secondary consideration.

This being said here are the latest modif.
(All are on develop only !)
1) running a macro as a GM without an actor selected will trigger a warning.
As a player your controlled character will be used as default is you don't have any owned character selected.

2) Added some feedback, when you roll a skill or push the development button.
Skill can be rolled individually for experience by clicking on them in the dev tab.

3) Added some controls for the GM only :
![image](https://user-images.githubusercontent.com/65915923/94326098-3b209f80-ffa2-11ea-99c2-9d33e006eb97.png)
The first button (the double up arrow) will lock/unlock any experience roll. Player will not be able to roll any skill for experience nor click the develop button unless this is active.
The second button (char with pencil) will lock/unlock the skills values. while this is on, no value can be entered for any skill.

I may get rid on the padlock button on character sheets and use those toggle instead.

**Comment by HavlockV** [comment]
All modif are on develop only
