### ISSUE TITLE
Hardcoded text in html templates

### ISSUE THREAD

**Issue by Gerbek** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#156]
Hi HavlockV,
I’ve been looking for the hardcoded text in the html template files in order detect those strings that appear in English and are not implemented in the .json language files. Below I specify the files and lines within each file that contain harcoded text. Thank you very much for developing this system, you are doing a very good job and I hope this helps to improve it :)

+ templates/actors/
	- creature-sheet.html
		Line 211 (both html 'title' and text)

+ templates/actors/parts
	- actor-weapons.html
		Lines 31, 32
	- npc-combat.html
		Lines 22, 24

+ templates/chat
	- con-check.html
		Lines 15, 19, 26, 29, 31, 37
	- roll.html
		Line 104
	- roll-result.html
		Lines 158, 166
	- san-check.html
		Lines 15, 18, 22, 28, 32, 38, 40
	- skill-card.html
		Lines 10, 11, 12, 13, 21, 22, 42, 58, 61, 63

+ templates/chat/combat
	- damage-result.html
		Line 62
	- melee-initiator.html
		Lines 198, 212, 222
	- melee-resolution.html
		Line 48
	- range-initiator.html
		Lines 36, 43, 54, 55, 57, 308, 314, 319, 348, 357, 411, 484, 500, 554

**Comment by HavlockV** [comment]
Thanks for the feedback, I will try to do as much as possible and push with the next release.

**Comment by Gerbek** [comment]
Thanks for taking care of this. There's no hurry, this was just a way to have these strings located so you can fix them when you have time.

**Comment by lozalojo** [comment]
Great work, Gerbek! today at our test I also noticed some text not translated at the chat, next time I'll write down to report it to HavlockV.

**Comment by HavlockV** [comment]
String updated available on dev
