### ISSUE TITLE
[Bug] Combat flow: lacks permission to update ChatMessage

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#161]
To reproduce:

I'm at dev 0.3.8
Character rolls Fighting Brawl, success.
Creature Figthsback, failure.
Character click to roll damage, then the following error is shown:

![](https://i.ibb.co/TYs0xYw/screenshot-66.jpg)

If the gm rolls character damage, no error occurs. I think that since the creature fightsback, the system thinks the damage is done by the creature and doesnt allow the character to roll damage. Not sure.

**Comment by HavlockV** [comment]
Does your user own AND has the actor as impersonated character ?

This issue usually came when the user is trying to 'speak' with a character that his main character. 

I just going for a few days shift, I'll have a look when I'll return. In the mean time just check that.

**Comment by lozalojo** [comment]
Yes, the player 1 is the owner of the character.

I've noticed also that it happens the same when the character (as player 1) tries to dodge an attack made by the creature (gm).

**Comment by Vass1979** [comment]
I cannot reproduce this error

**Comment by lozalojo** [comment]
Gabriel, ¿have you used stable or development?

**Comment by Vass1979** [comment]
Development

**Comment by HavlockV** [comment]
Beeing the owner only isn't enough, you also need to have that character as active PC to be able to 'make him speak'.
That can be check by clicking the player's name at the bottom left corner of the screen.

**Comment by HavlockV** [comment]
1) Giving ownership of actor 'harvey' to 'player 2' :
Right clik on the actor from the actor directory will bring the menu :
![image](https://user-images.githubusercontent.com/65915923/91935882-f4b38a00-ecee-11ea-85a0-026f4ca1dd65.png)
Selecting ownership right of the actor to 'player 2':
![image](https://user-images.githubusercontent.com/65915923/91935897-fed58880-ecee-11ea-838d-3001ae4307e5.png)

2) selecting 'harvey' as the character impersonating 'player 2':
Bringing up the player menu :
![image](https://user-images.githubusercontent.com/65915923/91936686-a8694980-ecf0-11ea-8173-2ed7d6d0caa7.png)
Opening the player configuration :
![image](https://user-images.githubusercontent.com/65915923/91936724-bae38300-ecf0-11ea-8e36-60fc565c5d0e.png)
Selecting the actor to impersonate and saving :
![image](https://user-images.githubusercontent.com/65915923/91936797-e1092300-ecf0-11ea-8b94-0809e87ff20e.png)

It's a design choice, to have the chat messages to be emitted as the character impersonating the player.
It can be moved to the ownership only. During testing this created some 'conflict' as an actor can be owned by different player but a player can only impersonate 1 exclusive character.
Hope this help.

**Comment by HavlockV** [comment]
Make sure that this is the case. If it still doesnt work please send a feedback.
