### ISSUE TITLE
[Bug] Localised dodge not working for creatures

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#162]
For creatures, combat flow does not recognize localised "Dodge", It only allows to dodge when the creature has the "Dodge" (in english) skill.

For characters, looks like it works, recognizing the localised skill "Esquivar" (in spanish).

**Comment by lozalojo** [comment]
I cannot replicate the bug, I close it and in case I see it again, I will reopen again.

**Comment by lozalojo** [comment]
This is the attack when the creature has its dodge skill in spanish, cannot use dodging (in white, cant use it).

![](https://i.ibb.co/B39Qky3/screenshot-67.jpg)

If I rename the skill (just rename to Dodge) to Dodge (in english), then I can use dodging (in grey, can use it):

![](https://i.ibb.co/Rb9v4Qj/screenshot-68.jpg)

**Comment by HavlockV** [comment]
Thanks for the report, I'll have a look at it.

**Comment by HavlockV** [comment]
Hola, just had a look at It.
Couldn't reproduce the bug easily.
The only case I can is if the keeper's language is different from the player's language. E.g keeper in Spanish client in English.
Could you please check that and give a feedback?

**Comment by lozalojo** [comment]
Yes, that's the case, I was testing language settings, and had the client in english and the server in spanish.

So all connected clients and gm have to setup the same language.
