### ISSUE TITLE
[Improvement]Pulp HP calculation

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#163]
So, this is a small issue, because you can always manually edit HP, but when you're bulk building stuff it's an extra step that we may be able to eliminate? SO here's the issue right now. In Pulp Cthulhu not everyone gets double HP.

- Investigators get double HP
- Major Villains don't get double HP
- Normal NPC's don't get double HP
- Mythos Monsters don't get double HP
- Mooks don't get double HP

So I was thinking, maybe double HP can be a toggle per character instead of across the rules system? Not sure how feasible that is and as I said NOT a priority right now as it can be fixed by manually editing the HP, but maybe something to consider waaaaay down the line when you don't have anything else to add to the system!

**Comment by HavlockV** [comment]
Only Investigators (characters) are now getting double HP
