### ISSUE TITLE
[Translation] Missing keys

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#172]
In chat-cards when development:

![](https://i.ibb.co/zJqHFSG/screenshot-201.jpg)
![](https://i.ibb.co/bFcZY72/screenshot-202.jpg)

**Comment by HavlockV** [comment]
Ok noted, I will include those in the language file. Thanks for feedback, appreciated !

**Comment by lozalojo** [comment]
Great, thank you!

**Comment by lozalojo** [comment]
Hi, automatic roll has been translated, but if you chose to roll skills individually, are still in english:

![](https://i.ibb.co/GnZY0pn/screenshot-207.jpg)

**Comment by HavlockV** [comment]
Missed that one...
Corrected for next release. 
I even added the Spanish localization (but they better be checked before release)
String are:
"CoC7.DevRollTitle": "Tirando desarrollo de {item}: {die}/{score}%",
"CoC7.DevSuccessDetails": "{item} se ha aumentado un {augment}%",
"CoC7.DevFailureDetails": "{item} NO se ha aumentado",

**Comment by lozalojo** [comment]
I will check, no prob, when there is an update I have a routine for comparing strings.
