### ISSUE TITLE
Character sheet missing Development button

### ISSUE THREAD

**Issue by macehkm** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#175]
upgraded to 3.8 and the Add Development Phase is missing and I cannot modify anything on the  Development tab sheet.

![image](https://user-images.githubusercontent.com/40439074/95667526-590b0a00-0b35-11eb-9221-21b9caf1e070.png)

Plus when I try to import the 1920 Character sheet it gives a message Cannot read Property "Items" Null.
I am on foundry  0.6.6 and Call of Cthulhu 0.3.8.  This happens in both windows 10 and linux.

**Comment by Vass1979** [comment]
Do you have development phase unlocked from the buttons on the left side?

**Comment by macehkm** [comment]
I try to click in the circles (buttons) but they don't do anything.   Is that what you mean?

**Comment by Vass1979** [comment]
No. Look to the toolbar at the left side of foundry. There is a button to
unlock. In

**Comment by macehkm** [comment]
OMG, I totally missed that.  Its working now.  I am too old to use technology lol
Thanks for the help, you all are doing an outstanding job with this module.
