### ISSUE TITLE
[BUG] Damage not displaying correctly

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#176]
So damage seems to calculate correctly (ie the numbers add up) but on the chat card it's not displayed correctly

![unknown](https://user-images.githubusercontent.com/470640/95678603-9b7c2780-0bc5-11eb-85dc-c0e1588de574.png)

**Comment by HavlockV** [comment]
Ok, thanks for feedback, will correct that ASAP

**Comment by HavlockV** [comment]
Corrected on dev
