### ISSUE TITLE
[Enhancement] More than one specializacion skills in occupations template

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#177]
Example: Artisan
Skills: Two Arts/Crafts skills of your choice

When creating the item.occupation Artisan, I cant drag'n'drop Arts/Craft twice, only one specialization skill allowed.

I do not know how to handle this

**Comment by HavlockV** [comment]
Yes indeed, skills can't be duplicated when they have the same name. That's indeed an issue for spec.
Will correct it, thanks for feedback.

**Comment by lozalojo** [comment]
What I've done is to create a group of skills with ALL specializations and let the player chose two

**Comment by Vass1979** [comment]
> What I've dont is to create a group of skills with ALL specializations and let the player chose two

All Art/Craft specializations? That's a lot! :D

Also, this would pose a problem to skills that also need a specialization like survival and science, right?

**Comment by lozalojo** [comment]
I have linked all specializations in the Art/Craft skill, so since all are grouped, it is just drag'n'drop.

**Comment by Vass1979** [comment]
Care to share how you've done that?

**Comment by lozalojo** [comment]
Sure, but in perfect Spanish:

![](https://i.ibb.co/9ctg8R5/screenshot-204.jpg)
Hi res:
https://ibb.co/2WNhnX4

**Comment by Vass1979** [comment]
I am a bit slow, apologgies.
So, is the container for all the specializations the art/craft skill? I don't get it :)

**Comment by lozalojo** [comment]
I've got:

1 skill for each specialization, in the image I show Dance (Danza), an specializacion of Art/Craft
1 generic skil Arts/Craft (Arte/Artesanía) with description, with links to all possible specializations (including Dance), there are about 15 different specializations/skills.
1 occupation item, with a "optional group skill" with all specializations I've created, and tell the system to chose 2 specialización between all possible. To create it, simple dragndrop skills to the specializations from the links in Arts/Craft skill to the occupation item.

This way, I can create the "Chose 2 Art/Crafts skills" artifact.

If it is still not clear, do not hesitate to ask. No prob!

**Comment by HavlockV** [comment]
Unspecified specialization can be added freely in Setup, Occupation and archetypes.
When selecting/creating those system will ask if you want to use an existing one (in case or archetype/occupation) or create a new one and specify it's base.
If the windows is closed it will be created as Any (you can change the generic name in the en.json)
