### ISSUE TITLE
[BUG] Credit calculation not working (0.3.8)

### ISSUE THREAD

**Issue by Gerbek** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#191]
Automatic credit calculation from Gear & Cash tab is not working anymore. The default values are fixed and do not seem to response to changes in the credit skill values.

**Comment by HavlockV** [comment]
Thanks for feedback, indeed there's a bug when returning credit value.

**Comment by HavlockV** [comment]
Corrected on dev branch

**Comment by Gerbek** [comment]
Thank you HavlockV!
