### ISSUE TITLE
Journal link on a skill not working!

### ISSUE THREAD

**Issue by rdsbrazil** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#194]
While the character sheet is unlocked to edit, i can see the journal link in the skill description
![image](https://user-images.githubusercontent.com/73025261/96337672-23977c80-105f-11eb-827d-0fc68188d594.png)
  but as soon as i lock the character sheet again, the link is gone 
![image](https://user-images.githubusercontent.com/73025261/96337676-2b572100-105f-11eb-8249-277ec8cbf38f.png)

**Comment by HavlockV** [comment]
Corrected on 3.9
This is a quick fix, waiting for the refactor of items and character sheets.
As a result, all links are now correctly parsed except for PDF foundry links.

**Comment by rdsbrazil** [comment]
is working perfectly, tks a lot! =)
