### ISSUE TITLE
Dealing damage to a character renders it uneditable

### ISSUE THREAD

**Issue by sharcashmo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#195]
Hi,

when in combat a character is dealed damage and he falls unconscious, it is no longer possible to unlock the character sheet and it is not possible to restore this character stats.

**Comment by Vass1979** [comment]
Did you try double-clicking the portrait?

**Comment by HavlockV** [comment]
Yes, that was for my group, loved the dramatic effect and the subsequent dialog :
- I'm dead
- Yes
- But I can't do anything more !
- No you're dead
- But I can't check my gear and notes
- Well being dead suck
- But I can't interact with my sheet anymore
- Nope, you're still dead...

That was fun but I recon it's not very practical and might be frustrating. I'll release a fix in 3.9 hopefully today.
In the meantime, only as a GM you can double click on the character portrait to remove that condition. If the character is dying, there will be a dice appearing that he can click which will trigger a CON check.

**Comment by HavlockV** [comment]
Players can now modify all status.
An option by has been added to prevent player from modifying their status.
Will be avail on 3.9

**Comment by sharcashmo** [comment]
Ha ha ha ha!

That's great!

Now I've tried double clicking on the portrait and it worked. Thanks!

**Comment by sharcashmo** [comment]
Now that I know how it works, it was fine the old way too. It's just that I didn't know about the double click.
