### ISSUE TITLE
[Bug] No list of specialization/no reference to skill you are creating an specialization for

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#214]
When an occupation is applied to a character, if it contains specialization skills like "Science", the wizard ask you to create a new specialization (like Engineering), the problem is that the window does not show which skill we are creating an specialization for.

Creating a new Art/Craft, the dropdown shows only one specialization:
![](https://i.ibb.co/xsN62gS/screenshot-98.jpg)
But I've got lots of specialization:
![](https://i.ibb.co/QMfnyTB/screenshot-99.jpg)
Sometimes it does not detect any specialization, this is a new Science:
![](https://i.ibb.co/R0ZtmMs/screenshot-100.jpg)
And I've got lots of specializations:
![](https://i.ibb.co/TwLnLM0/screenshot-101.jpg)
For example Chemistry:
![](https://i.ibb.co/R4sQPGp/screenshot-102.jpg)

So:
1. Fix how the list of available specialization is created.
2. Show somewhere at the creation window what skill you are creating a new skill for, to know if it is Other language or Science.

**Comment by HavlockV** [comment]
It actually appears on the window's title, but in Spanish it gets too long and is cut, especially if you use the popOut module.
We have actually the exact same issue in French, for the same reason.
The full title is "Seleccione/cree la especialización {specialization} de la habilidad", where {specialization} is the spec name.
I'll arrange something.

Thank for the feedback.

**Comment by lozalojo** [comment]
I will change it for "Especialización de {specialization}", you might do the same for French.

Have you checked why the list of specializations only contains some (or none) of them?

**Comment by HavlockV** [comment]
Because they don't use the compendium, the system is only retrieving occupations from the PC sheet.
In a very near future I will add this, the possibility to feed a specific compendium to the system so he can retrieve and use them. I haven't finalized how to exactly do that in a convenient way.

**Comment by lozalojo** [comment]
Oh, I understand, pretty obvious.
