### ISSUE TITLE
[Suggestion|Enhancement] Adding button (dice) to generate Luck automatically

### ISSUE THREAD

**Issue by sharcashmo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#221]
Hi,

in many games using pregenerated characters _Luck_ has to be calculated at the very beginning of the game by rolling 3D6*5.

It could be an enhancement to add a way to automate this roll, instead of rolling it by hand and updating the sheet with the luck value.

**Comment by HavlockV** [comment]
Will have a look at it (adding and option to roll luck when it's null).
In the meantime you can use the 'setup' items (on is provided in the Item example compendium)
Dropping it on a sheet will allow you to roll all characteristics, luck and add the skills to a blank character sheet.
Thanks for the suggestion.

**Comment by sharcashmo** [comment]
Thanks for your suggestion, too. I'm new to Foundry and there're a lot of things that I still don't know.
