### ISSUE TITLE
[Bug|Enhancement] "Conflict" PDFoundry

### ISSUE THREAD

**Issue by sharcashmo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#223]
Hi,

when module PDFoundry is active, creatures and npc use the PDFoundry sheet instead of the CoC7 one, so a blank page is shown instead of the character sheet.

It can be solved easily by assigning the CoC7 sheets as the default ones. This info is stored in settings.db at core.sheetClasses. Would it be possible that this system add this info to settings.db?

This is the needed entry:

`{"_id":"YqVlczKaQKR6Nfht","key":"core.sheetClasses","value":"{\"Actor\":{\"creature\":\"CoC7.CoC7CreatureSheet\",\"npc\":\"CoC7.CoC7NPCSheet\"}}"}`

**Comment by HavlockV** [comment]
Hi sharcashmo. Thanks for the feedback.
No, I can't change that, settings.db is not a system database, it's a world specific database.
I tried to reproduce that bug but wasn't able. The only case I saw where the sheet class was overridden is when there's a bug in the CoC7 system.
If you manage to reproduce this, please check the console (F12) for error.

**Comment by sharcashmo** [comment]
Hi!

I found which is the problem and why PDFoundry conflicts with NPC and Creature sheets.

It is caused by the registering of these actors sheets. At coc7.js both

```
	Actors.registerSheet('CoC7', CoC7NPCSheet, { types: ['npc'] });
	Actors.registerSheet('CoC7', CoC7CreatureSheet, { types: ['creature'] });
```

should be changed to

```
	Actors.registerSheet('CoC7', CoC7NPCSheet, { types: ['npc'], makeDefault: true});
	Actors.registerSheet('CoC7', CoC7CreatureSheet, { types: ['creature'], makeDefault: true});
```

I'm having problems with synchronizating my fork with your repo. As soon as I can solve it I'll write a patch for it.

**Comment by HavlockV** [comment]
Hi sharcashmo,
Thanks for the feedback. That was effectively missing in the code.
It's corrected now and will be on the next iteration.
