### ISSUE TITLE
Combat Tracker Doesn't Honour Simple CoC Initiative Rule

### ISSUE THREAD

**Issue by Dick-K** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#228]
The 7E rules say that initiative is in DEX order, with initiative for equal DEXs being decided by _Fighting Skill_ ordering. However, on Foundry 0.6.6 and the CoC 4.3 sheet, equal DEXs appear to be decided by lexically sorting the token name, and I can't find any way of manually reordering combatants by mouse drag. Is this something that can be handled by the sheet mechanism?

**Comment by Vass1979** [comment]
![image](https://user-images.githubusercontent.com/470640/97766091-df9b8180-1b0c-11eb-8080-6bf57773a42e.png)

It does not say Fighting, it says Combat Skill. And that's the problem. What are we comparing? Brawl? Handgun? Rifle Shotgun? All of them combat skills

**Comment by Dick-K** [comment]
You're right, I guess the spirit of the Keeper's Guide is tuned to tabletop play where these grey areas are mediated by the GM. Leix here, btw, 'Leix' was already taken on GitHub.

**Comment by HavlockV** [comment]
Hi Leix/Dick-K
First of all thanks for the feedback
As Vass1979 mentioned it, at the time of initiative roll the skill that will be used is no known, therefor it's not possible to arrange initiative at that point.
It's possible in foundry to manually edit the initiative result (right click on the combatant in the initiative tracker, then Update Combatant)

**Comment by Dick-K** [comment]
Completely understood, thanks for looking at the issue.
