### ISSUE TITLE
Token Images and Portraits not appearing on chat card for ranged weapons

### ISSUE THREAD

**Issue by Dick-K** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#231]
I've noticed with the latest sheet (0.4.3) and either 0.6.6 or 0.7.5 of Foundry, that ranged weapons don't display the token/portrait of the aggressor in the chat card, while melee weapons do. I have tested this with the flags set correctly on the sheet configuration. This is regardless of whether there's an image for the weapon in its item description or not. Melee weapons are fine in this regard.

**Comment by HavlockV** [comment]
Thanks for the feedback, appreciated !
Displaying if the portrait on range card has been updated in 0.4.4

**Comment by Dick-K** [comment]
Thank you very much...I really appreciate it.
