### ISSUE TITLE
[Enhancement] When using Optional Initiative Rule display degree of success instead of number.

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#234]
![OptionalInit](https://user-images.githubusercontent.com/470640/98416577-3954fc00-2077-11eb-9383-13e6f91c5cbc.jpg)

**Comment by HavlockV** [comment]
Implemented on 0.4.4.
Setting added to display text or value
Thanks for suggestion
