### ISSUE TITLE
[BUG] Development Phase not working

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#235]
So this is a character where I manually entered skills values as it is from an ongoing campaign, ie I did not use the character creation from the ruleset.

![image](https://user-images.githubusercontent.com/470640/98435836-47823700-20ce-11eb-9e95-5eb901e5beaa.png)

Here is the exported actor data:
https://drive.google.com/file/d/1GVhCvb0Hqtyinys6qFhLFo_TSTgbvZmO/view?usp=sharing

Also NO console errors I should add

**Comment by HavlockV** [comment]
Bug corrected on 0.4.4
Thanks for the feedback !
