### ISSUE TITLE
[Enhancement] Have Weapons with Charges

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#236]
I am trying to create a weapon where my player can choose how many CHARGES he wants to expend (1, 2 or 3) and then fire a SINGLE attack roll to determine hit for all 3. Is there a way to emulate that with the current weapon system cause I haven't found one (YES, I am running a very pulpy game :stuck_out_tongue: )

![taser](https://user-images.githubusercontent.com/470640/98435983-561d1e00-20cf-11eb-9c1c-617182fbb078.png)

**Comment by joaovscorreia** [comment]
@Vass1979 this type of rule is official in any of the Chaosium books?

**Comment by joaovscorreia** [comment]
I will be closing this Issue for not having an answer. If you want it to be reopened in the future, just say so! :)
