### ISSUE TITLE
[Bug] Can't make skill checks from sheet unless I have Dice so Nice turned on

### ISSUE THREAD

**Issue by Hamitay** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#244]
I had some issues with running skill checks from a character sheet. By investigating the console, the problem seems to be on this line:

``const syncDice = game.settings.get('CoC7', 'syncDice3d')```

By inspecting the game.settings map in the console it appears there is really not a key set to "CoC7.syncDice3d".

If I turn on the DiceSoNice module, it starts working. If if turn it off, it stops working again with the same exception.

Not sure if this is something in my environment, though.

If it helps:

* I'm running in a docker container inside a DigitalOcean droplet running ubuntu.

**Comment by HavlockV** [comment]
Thanks for the feedback.
Testing method of the availability of DsN has been changed.
This should be working on next iteration.
