### ISSUE TITLE
[Bug] Creatures with non-integer multipliers

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#245]
... produces non-integer mean values.

So (3d6+3)*7.5 might result in a mean attribute of 97.5

I realized when entering bestiary (common animals).

**Comment by HavlockV** [comment]
Thanks for the feedback.
Indeed, when rolling that kind of formula the decimals were not removed from the result.
Corrected, will be pushed on the next iteration.

**Comment by lozalojo** [comment]
Works, thank you!
