### ISSUE TITLE
Occupation calculation error?

### ISSUE THREAD

**Issue by isogulaleb** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#246]
Hello, First of all, thanks for your excellent work, the only reason I changed to FVTT from Roll20 is that you did this development for Coc7ed. 

I created 2 characters by modifying the sample occupation item and drag&drop it to the charsheet - it worked like a charm, calculating personal and occupation skill points. I created a third occupation, same method, I did everything the same and it does not calculate skill points. It drives me crazy. First I thought it is because this occupation does not contain specializations (no validation required at the ned of the procedure) but I tested it by modifying the item and it seems that not this causes the error.
Archeologist works
![image](https://user-images.githubusercontent.com/25512046/98565386-d9946600-22ad-11eb-9623-7ec561020327.png)
Entertainer works
![image](https://user-images.githubusercontent.com/25512046/98565485-f6309e00-22ad-11eb-9173-7d785a3b2ecc.png)
Bloody pilot does not work :(
![image](https://user-images.githubusercontent.com/25512046/98566125-b28a6400-22ae-11eb-8469-2e3c9fb4ef2e.png)

Thanks for any ideas!
Cheers

**Comment by Vass1979** [comment]
|Question for you, if you restart Foundry and try your occupation on a new character, does it work?

**Comment by isogulaleb** [comment]
> |Question for you, if you restart Foundry and try your occupation on a new character, does it work?

Nope, I tried this too.

**Comment by Vass1979** [comment]
Can you export your occupation to a JSON and post it here?

![image](https://user-images.githubusercontent.com/470640/98573651-0301c180-22af-11eb-928c-4ea9f7e9d75f.png)

**Comment by isogulaleb** [comment]
Sure, here you are!
[fvtt-Item-Aviator.zip](https://github.com/HavlockV/CoC7-FoundryVTT/files/5512199/fvtt-Item-Aviator.zip)

**Comment by Vass1979** [comment]
Yep, looks like a bug, When I dropped your file into a character it marked the occupations skills correctly, but did not calculate points or fill in the occupation field.

**Comment by Vass1979** [comment]
OK, UPDATE. I used one of my own occupation files and it works fine. Weird. Maybe Havelock can shed some light?

![image](https://user-images.githubusercontent.com/470640/98575724-71478380-22b1-11eb-9af6-719423419361.png)

**Comment by isogulaleb** [comment]
> OK, UPDATE. I used one of my own occupation files and it works fine. Weird. Maybe Havelock can shed some light?
> 

Yes, I made two others previously, those worked fine too.
![image](https://user-images.githubusercontent.com/25512046/98576275-9987b000-22ba-11eb-89ef-43c7abc9d57e.png)

**Comment by HavlockV** [comment]
Hi Isogulaleb
First of all thanks for the feedback, appreciated.
I had a look, for some reason your skills don't have an internal field called 'flag'.
A check for integrity of datas is missing when a skill is created from a specialization (in your case that's the Pilot (Any) skill'. That's a miss from the system, I'll patch it ASAP.
But it's normally not possible to create a skill without that field. Where do you skills come from and how did you add them to your occupation ?
Can you also send an export of your Pilot (Any) skill.

**Comment by HavlockV** [comment]
OK I think I got it !
You got that skill from the skills compendium provided with the system.
I created that compendium manually and missed the flag field in some specs.
I'll push a new version in 1h to correct that.
In the meantime you can work around it by creating your own Pilot skill :
Name : Any or Pilot (Any),
Specialization property enabled,
Specialization name : Pilot

**Comment by isogulaleb** [comment]
whoa! you are the greatestest! :) thanks mate! (so is the pilot skill the culprit? I will try, thx)

**Comment by isogulaleb** [comment]
> OK I think I got it !
> You got that skill from the skills compendium provided with the system.
> I created that compendium manually and missed the flag field in some specs.
> I'll push a new version in 1h to correct that.
> In the meantime you can work around it by creating your own Pilot skill :
> Name : Any or Pilot (Any),
> Specialization property enabled,
> Specialization name : Pilot

Yes, deleting Pilot from the Aviator occupation solved the problem, skill points are calculating. Thanks!
