### ISSUE TITLE
Combat tracker does not update the tracked resource for the final damage?

### ISSUE THREAD

**Issue by isogulaleb** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#249]
Hello, another question here :/

I experience that the final blow taken by a combatant does not get recorded (shown) in the combat tracker tracked resource value... is this a bug or a feature? Or this is a base module functionality and has nothing to do with your CoC implementation?

![image](https://user-images.githubusercontent.com/25512046/98665074-76f1a780-234b-11eb-99d0-0560f1d82958.png)
Dr. Jones inflicts 23 points of damage to de Mendoza, token shows 0 hp)

![image](https://user-images.githubusercontent.com/25512046/98665110-81ac3c80-234b-11eb-81b3-1324f9ae3301.png)
(combatant de Mendoza's hp still shown as 15 though he is as dead as a rock) 

Thanks!

**Comment by HavlockV** [comment]
Hi isogulaleb,
As far as I know this is the way foundry is designed. Your tracked resources will be updated when you change something in the combat tracker (hit the next arrow or toggle status for example).
Not sure if there's a way to force a refresh of the combat tracker when an actor is updated.

**Comment by isogulaleb** [comment]
Thanks Hav, it is weird because whenever a hit is registrated the tracked resource number is decreased accordingly, only the last, final deduction seems to be missing... cannot phathom the reason why...
