### ISSUE TITLE
[BUG] Dice so nice does not get triggered when rliing damage from a chat card

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#252]
I just noticed, when I roll damage after a successful weapon hit, it doesn't roll dice so nice. Also it shows the total result only and not the number rolled on each dice.

**Comment by HavlockV** [comment]
Thanks for feedback, corrected on 0.4.5
Thanks for feedback !

**Comment by Vass1979** [comment]
Still doesn't roll dice for me when I click Roll Damage in the chat card

**Comment by HavlockV** [comment]
Can you confirm that is for melee damage. 
Range damage will not trigger damage rolls.
The main reason being that in some cases (MG/SMG) this will may create a tremendous amount of dices to roll
