### ISSUE TITLE
[Bug] The Furnace module incompability

### ISSUE THREAD

**Issue by frondeus** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#253]
VTT version: 0.7.7
CoC7 version: 0.4.4
Furnace module version: v2.6.0

Whats wrong:
When furnace module is enabled I cannot drop Occupancy into actor sheet. All other things like setups, items, weapons are working correctly.

Console logs:
```
Uncaught (in promise) TypeError: Cannot read property 'hash' of undefined
    at Object.t.options (h.min.js:1)
    at Object.c (handlebars.min.js:27)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29), <anonymous>:13:243)
    at c (handlebars.min.js:27)
    at d (handlebars.min.js:27)
    at e (handlebars.min.js:28)
    at foundry.js:6000
    at async Function.create (skill-selection-dialog.js:26)
    at async CoCActor.createEmbeddedEntity (actor.js:582)
```

Disabling The Furnace fixes the problem

**Comment by Vass1979** [comment]
wouldn't that need to be fixed on The Furnace module side?

**Comment by frondeus** [comment]
Maybe. I saw it failing on coc7 js file so I guessed its the proper project to create an issue. If not, then I'll create similar one in The Furnace project

**Comment by HavlockV** [comment]
I'll have a look at it ASAP, thanks for the feedback

**Comment by joaovscorreia** [comment]
@frondeus, can you please confirm if this issue is still valid?

**Comment by joaovscorreia** [comment]
@frondeus, I'm closing this Issue since this module has been discontinued and replaced with multiple other modules.
