### ISSUE TITLE
[Bug] Skill chat-cards

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#256]
I'm on dev 0.4.5 over 0.7.7 core, localization: spanish:

When I make a skill check:

![](https://i.ibb.co/4Vt4B3G/screenshot-210.jpg)

Issues:

1. Missing "(" at the begining of the % value.
2. Sanity and Luck are not translated, only skills are translated.

**Comment by HavlockV** [comment]
Thanks for the feedback.
I could not reproduce this...
The "(" is hard-coded in the HTML file.
Could you try to re-pull the latest 0.4.5 from develop an try again.

**Comment by lozalojo** [comment]
Concerning point 1: you are right, it is a an error in the key CoC7.CheckResult at es.json, I have fixed it
Concerning point 2: Seems that the only rolls that are not translated are Luck and Sanity:

![](https://i.ibb.co/ZWz3JqY/screenshot-216.jpg)

**Comment by HavlockV** [comment]
Ok, there was a bug in the check subroutine. Corrected !
Thanks for feedback !

**Comment by lozalojo** [comment]
Tested, it works now, thanks!
