### ISSUE TITLE
[Bug] Maestro item-sound trigger compatibility

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#257]
I'm on dev 0.4.5 over 0.7.7 core, localization: spanish:

Maestro module allows to attach sounds to items:

https://foundryvtt.com/packages/maestro/

For example, you can attach a "colt .45" a colt45.mp3 file, so that each time you run the skill to use the item, the mp3 is triggered.

Seems that it does not work with chat-cards, it works for simple rolls.

Example:

![](https://i.ibb.co/fFMFK7G/screenshot-212.jpg)

If I click in the automated chat-card flowsystem (in red), it does not trigger the sound.
If I click in the standard skill roll, it does trigger the sound.

Not sure this is an issue of CoC7th or Maestro, but since I asked you at discord and you told me you'll take a look at it, I open an issue just as a reminder and expanding information.

**Comment by joaovscorreia** [comment]
@lozalojo can you please confirm if this issue is still valid?

**Comment by lozalojo** [comment]
@castanhocorreia , just tested, to reproduce:
1. Activate Maestro
2. Settings: enable item tracks and items playlist
3. Create a sound under playlist item called revolver .32 and assign a appropiate sound.
4. Open pc, open a weapon revolver .32, click item track, assign the revolver .32 sound.
5. Click on the weapon to initiate combat flow, the sound should trigger, but it doesnt

Combat cards probably denies Maestro from seeing the item is being used, not sure if it is a CoC issue or Maestro's

**Comment by bdenne2** [comment]
I believe this is an issue within Maestro. https://github.com/death-save/maestro/issues/143#issuecomment-922403935
I've made a comment there with my educated guess on what's wrong.

**Comment by bdenne2** [comment]
Though, to be fair, the name of the attribute to use to identify the actorId within the chat message sent after attacking someone _could_ be considered an issue within either repo?

**Comment by eclarke12** [comment]
@bdenne2 I've made some changes to Maestro's chat message parsing in the upcoming release, however a bug I've noticed in COC is that if you "roll" an item from an Actor sheet without a token selected, the `speaker` attribute does not seem to be correctly constructed on the `message`, notably the `actor` parameter is not set, so the message just appears to emanate from the user.

It appears to be working when the actor's token is selected when the item is rolled.

**Comment by lozalojo** [comment]
Just tested RC 0.7.6 with a CoC item used in the combat flow chat message and it works, havent tested the rest of maestro's features, nor the bug mentioned concerning non-owned tokens, thou. Thanks @eclarke12  and, as always, the guys at the MIS.

**Comment by joaovscorreia** [comment]
Thanks for keep us informed, @lozalojo!
