### ISSUE TITLE
[Bug][Dev] Difficulty not applied to roll request

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#258]
I'm on dev 0.4.5 over 0.7.7 core, localization: spanish:

Requesting a Hard Difficulty check:

![](https://i.ibb.co/r5sd2cR/screenshot-214.jpg)

The chat-card says "normal difficulty", the luck spending dialog also says "a normal success is required"

**Comment by HavlockV** [comment]
Corrected on the new push on develop !
Thank for feedback

**Comment by lozalojo** [comment]
Tested, it works now, thanks!
