### ISSUE TITLE
[Feature][Dev] Allow roll request in roleplaying scenes where there are no tokens

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#259]
I'm on dev 0.4.5 over 0.7.7 core, localization: spanish:

Maybe this is not possible, but currently @coc7.check and @coc7.sancheck works only (at least for me) if you have an active token in the current canvas/map.

If you are ropleplaying investigation parts without using a map with associated tokens and you throw a roll request for "Accounting", the players cant use the chat-card since they havent a token in the scene.

**Comment by HavlockV** [comment]
Player will be allowed to trigger check even if he has no controlled token. He must have at least one owned actor.

**Comment by lozalojo** [comment]
You mean in a future fix? Currently only works when the player has an owned token in the scene.

**Comment by HavlockV** [comment]
I just pushed a new update on develop. I can't remember if it was before or after.
It should be working if you logon as a player with an impersonated actor/owned character.
It will trigger the check for the impersonated actor.
This will not work when logged as a GM. As a GM you must have a token on a canvas and select it to trigger the check for that token.

**Comment by lozalojo** [comment]
Tested, it works, but newly entered players have to select the player they own in the Players configuration at the left-down corner of the scene.

**Comment by lozalojo** [comment]
I consider the issue closed, but I'd warn in the readme that the player might have a controlled character because by default, the intro dialog (the one that allows the player to select the colour) does not select any character and players enter the game without a controller actor.

Players can select an actor in the left-down users connected list + right-click + configure player + select controller actor between a list of actors with ownership permission.
