### ISSUE TITLE
[Feature][Dev] Translation for {type} rolls on chat-cards

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#266]
Add keys to translate the keys "skill" and "charac" in the chat-card of a requested roll with no description:

![](https://i.ibb.co/vXqbwJY/screenshot-217.jpg)

I know I can circunvent this issue by removing the {type} string from CoC7.LinkCheckDiff, but it is better to have a key for that.

Sorry for being so picky

**Comment by HavlockV** [comment]
No problem.
The new version on develop should correct that.
I will check this ASAP.
Thanks for your help testing this.

**Comment by lozalojo** [comment]
New version removes the reference to type, so not an issue anymore, I close the issue
