### ISSUE TITLE
[Bug][Dev] Characteristics not detected in locales anymore for @coc7.check roll requests

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#269]
In spanish DEX is DES.

Until last update on dev, it worked this way:

@coc7.check[type:charac,name:DES,icon:fas fa-dice,difficulty:+,modifier:-]

But since last update, this does not work anymore, showing "Undefined" when dragndrop to the chat.

It works in english:

@coc7.check[type:charac,name:DEX,icon:fas fa-dice,difficulty:+,modifier:-]

I dont know if this is intentional, no problem, but since It worked in specific locales until now, I dont know if something was broken in a recent modification.

**Comment by HavlockV** [comment]
No that's a bug. I'll have a look at it.
Thanks for feedback.

**Comment by HavlockV** [comment]
OK I just had a look at it. It does the same in FR, link showing undefined, but check still working
I'll work on it.

**Comment by HavlockV** [comment]
This is corrected on 4.5, links will understand 'local' names.
They still will be created using system keys (english names) when drag/drop

**Comment by lozalojo** [comment]
It works now, thanks
