### ISSUE TITLE
[Bug?][Dev] No @coc7.skill when CTRL+dragndrop characteristics/SAN/Lck

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#270]
Open a journal. Open a character sheet.

CTRL+dragndrop a skill from the character sheet to the journal creates the @coc7.skill roll request.
CTRL+ dragndrop a characteristic ... does not create anything in the journal.
The same for SAN/Lck, no @coc7.sanloss creation at the journal.

Maybe I am understanding wrong from the readme file, but I thought it worked that way.

**Comment by HavlockV** [comment]
CTRL+drag from sheet only works for skills so far.
CTRL+click will post a message in the chatlog, you can then drag that message on a journal/sheet

**Comment by lozalojo** [comment]
I leave this issue open as a remainder in case you plan to add this as a new feature in a near future. In case you dont, please, close it.

**Comment by HavlockV** [comment]
Implemented on 4.5
