### ISSUE TITLE
Dice so Nice - displaying rolled number immediately despite setting

### ISSUE THREAD

**Issue by michaelkayo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#271]
Dice so Nice module has a tickbox "Display chat messages immediately" and allows 3d dice roll to finish before revealing the values. It follows setting when separate dice are rolled. However, when any roll is made from character sheet, it is displaying the rolls simultaneously. I do not know of how it interacts with other RPG systems but it works properly in DND 5e.

**Comment by HavlockV** [comment]
CoC is using its own dice. I will add the option to delay messages publishing after DsN dices stopped rolling.

**Comment by krusty4president** [comment]
> CoC is using its own dice. I will add the option to delay messages publishing after DsN dices stopped rolling.
Hi. I also detected this. When do you think this will be implemented?

**Comment by BabyfaceFinlayson** [comment]
Hopefully a fix on the way?

**Comment by Fmerrick** [comment]
One more vote for this fix! My players love the 3D dice in Foundry and that little delay between rolling the dice and them stopping moving before the rolls show up in the chat is that sweet little extra in 5e. Also, @HavlockV , is there any way to donate to you? I support good things when I see them and this is a good thing! So much better than the Roll20 implementation.
