### ISSUE TITLE
[Bug][Dev] Large tables not displayed correctly

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#272]
New world, new Journal Entry, I create a table 3x9 and save.

If I open the journal entry I see this:
![](https://i.ibb.co/zPZcZN4/screenshot-220.jpg)
If I edit the journal entre I see this:
![](https://i.ibb.co/Xx5ZSC6/screenshot-221.jpg)

I've tried with other system (SWADE and DND5) and the table is ok in viewing/editing mode. In CoC looks like the viewing mode does not show tables correctly.

Can anyone reproduce this?

**Comment by lozalojo** [comment]
More tests: I can see the tables in viewing mode in 0.4.4, so it is a problem of the lastest dev version.

**Comment by HavlockV** [comment]
Ok; That's a bug of the sheet parser.
I'll correct that and post something when it's available on develop.
Thanks for the feedback

**Comment by HavlockV** [comment]
Bug corrected on develop
Tables and other big HTML elements should display correctly now.

**Comment by lozalojo** [comment]
Now it works, thanks!
