### ISSUE TITLE
[Bug][Dev] Difficult missing in chat-cards for roll requests

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#275]
Seems something is wrong with chat-cards of roll requests:

"CoC7.CheckResult": "{name} check ({value}%) - {difficulty} difficulty",

![](https://i.ibb.co/8NhYzxH/screenshot-135.jpg)

The {difficulty} part is missing, also

"CoC7.SuccessRequired": "{successRequired} success required.",

{successRequired} is missing

**Comment by HavlockV** [comment]
I couldn't reproduce this bug. Do you by any chance still have the link clicked to trigger that check ?

**Comment by lozalojo** [comment]
HavlockV, looks like the problem is when you set difficulty:0 or leave it blank, it does not "detect" it as regular.

This doesnt work:
@coc7.check[type:skill,name:Accounting,difficulty:0,modifier:0,icon:fas fa-dice]{ Accounting}
This works:
@coc7.check[type:skill,name:Accounting,difficulty:+,modifier:0,icon:fas fa-dice]{ Accounting}

![](https://i.ibb.co/mb0DmTt/screenshot-226.jpg)

For testing purposes: 1920s example character sheet, english, no module loaded.

**Comment by HavlockV** [comment]
So finally understood the problem. The 0 was wrongly interpreted triggering and invalid difficulty check.
Corrected now.
Thanks for your feedback.

**Comment by HavlockV** [comment]
Corrected on 0.4.6
