### ISSUE TITLE
[Question] SETTINGS.PulpRulesHint

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#286]
If pulp rules are already fully implemented, please remove the early implementation:

"SETTINGS.PulpRulesHint": "Alow the usage of Pulp Rules (Archetype, Talent, HP), !early implementation!",

I think you added it when the pulp rules were on development and not sure if the work is finished, I guess so, since it works perfectly.

**Comment by joaovscorreia** [comment]
@lozalojo, the Pulp rules are not yet fully implemented.
