### ISSUE TITLE
Wrong partial name

### ISSUE THREAD

**Issue by sharcashmo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#290]
Branch develop

Partial `actor-skills-v2.html` is registered as `actor-skills-v2.html`, but the actual file is named `actor-skills-V2.html` (note the wrong case in v2 vs V2). It works on Windows, but it fails on Linux as filenames are case sensitive.

**Comment by HavlockV** [comment]
Thanks for feedback, all names changed to lowercase.
Will be on the next release
