### ISSUE TITLE
[Feature] Compatibility with DsN styles

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#291]
Currently independently from which style for dice you select in Dice so Nice options, the dice actually rolled when clicking an skill are the white and orange ones, you cant use any other dice style.

Is it possible to add support for DsN styles?

**Comment by Fmerrick** [comment]
Go to Configure Settings, System Settings, and scroll to the bottom to the DsN settings. Delete the colorset settings, leaving blanks, then save. It should then start to default to your standard DsN style options.

**Comment by lozalojo** [comment]
Ops, thank you, I didnt know about this fix.

Not sure if it is a bug or it is something inherent to the DSN support on CoC, so I leave this open.

**Comment by HavlockV** [comment]
No the dice color are hard coded in the system.
There's 4 different dice with default values :
- units: white
- normal tens: foundry
- bonus tens: bronze
- penalty tens: bloodmoon
This can be changed in CoC7 settings. They are 'world' wide, I could make them user wide, I'll  check that.

**Comment by Fmerrick** [comment]
@HavlockV This is so strange. Deleting the preset colors and leaving blanks seems to work for me. In other words, the dice rolls then use whatever colors I have set in DsN. This works both for rolls from the character sheet and from the dice tray. This includes rolling the appropriate number of dices based on disadvantage/advantage and calculation difficulty level. Maybe I'm misunderstanding the problem?

**Comment by lozalojo** [comment]
For me too, leaving CoC/DsN options blank, changing the dice at the DSN configuration works

**Comment by HavlockV** [comment]
The settings are world wide, meaning that if you change it, it changes for all players.
Indeed if you leave one setting blank it will fall back to the default DsN style for that dice.
I can make this setting available per client and not per world, then each player can individually set/override the setting and not only the GM.
DsN doesn't know penalty/bonus/tens dice and will use the same style for each of those dice.

**Comment by lozalojo** [comment]
Oh, now I understand that setting, ok, then I close this issue as it is not a bug
