### ISSUE TITLE
[Feature] Request INT (Idea) check when 5+ SAN points are lost

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#292]
When a character loses 5+ SAN points, an INT  (Idea) roll is requested:

If failed: no temporary insanity
If succeed: temporary insanity

Currently, if 5+ lost. temp insanity is automatic, independently from the INT roll, which forces to remove the temp insanity tag when INT roll fails.

**Comment by HavlockV** [comment]
Yes, that's also in the flow chart somewhere I think :
https://1.bp.blogspot.com/-BNTWq7aI8ig/Xdl3op9bj5I/AAAAAAAAKXg/zOGaV1HvynE3RdX1usnH6-fGqLbcv5d3ACLcBGAsYHQ/s1600/SAN-flowchart%2B-%2BTheodor%2BPaues.jpg

**Comment by HavlockV** [comment]
Implemented on 0.4.8
