### ISSUE TITLE
[Feature] Roll table when temporary insanity

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#294]
When a character gets the temporary insanity state (succeding an INT roll after having lost 5+ COR), he has to roll in a table for temporary insanity.

I know this table cant be included in the system since it is copyrighted content, but I suggest:

Add a CoC system option "Select table for temporary insanity episodes" with a drop-down menu that allows to select a table created in the world.
If a table is selected in the system option, then incorporate this table roll in the SAN automation (after succeed the INT roll and applied the status, create a chat card for roll for temporary insanity episode", click would roll in the table.

This requires keepers to create by themselves the temporary insanity table, which probably they already do when gming CoC.

This is just an idea, please consider if it is possible to add such a thing.

**Comment by HavlockV** [comment]
Thanks for the suggestion, yes the all SAN system will need some love after I finish dealing with my beloved CSS.
I have chartflow also that I plan to implement someday

**Comment by Vass1979** [comment]
As long as it's optional I don't mind. This is a bit too much automation
for me. Sometimes I like to choose an appropriate insanity instead of
rolling on the table.

**Comment by lozalojo** [comment]
> As long as it's optional I don't mind. This is a bit too much automation for me. Sometimes I like to choose an appropriate insanity instead of rolling on the table.
> […](#)

Yup, maybe an option might be the card to let you "choose episode" or "roll episode"

**Comment by HavlockV** [comment]
Usually I put buttons on the chat card that are only visible to GM (e.g. on the combat card).
I can add that button roll table, if GM don't want to use it he can just ignore it.

**Comment by HavlockV** [comment]
Implemented on 0.4.8
