### ISSUE TITLE
[Bug] displayActorOnCard world setting is ignored in some chat cards

### ISSUE THREAD

**Issue by sharcashmo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#295]
The displayActorOnCard world setting is ignored in some cards. Combat cards do hide actor when this setting is disabled, but chat-message.html template does not.

**Comment by HavlockV** [comment]
chat-message.html is not used anymore. Will ve removed on the next release.
I have to cross check but if you see a chat portrait on a regular chat card it may be because of an addon.
The option for displaying the chat portrait is only used for combat chat card.
