### ISSUE TITLE
[Feature/Bug] Is throw skill a combat skill?

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#297]
Throw is used to throw a dinamite stick, but it is not a specialization of neither Fighting or Firearms.

Solutions:
To include it in Firearms, but it is shown as a firearms skill specialization, which is not consistent with the character sheet.
To tweak its properties to: "combat":true,"fighting":true,"firearm":false, but doing this way it does not show in the drop down menu fo selection of its related skill

![](https://i.ibb.co/QcBs4q8/screenshot-13.jpg)

I think it is something in the system that divides combat skills between melee and firearms, and throw does not fit.

Also, is it a way to define range based on STR? data.str.value*0.15, for instance?

**Comment by lozalojo** [comment]
Ops, I've just noticed that I can set it as Combat + Firearms and remove specialization to make it a range attack skill.

Im still lost at range, thou

**Comment by HavlockV** [comment]
It's really up to you. Flagging it as combat you'll have it in the combat tab, will be able to select it for weapons.

**Comment by lozalojo** [comment]
Perfect, I close the issue
