### ISSUE TITLE
[Question] Translation of Archtype and Abilities

### ISSUE THREAD

**Issue by Barti-meaus** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#300]
Hello,

I would like to help to translate the system to German. I found the json for UI but nothing I could translate the archetypes and abilities, where is it located or is there any way to integrate the translation in the lang .json files?

Furthermore, I just want to ask if you prefer a specific way of contribution e.g. anything which is important to mention in the pull request?

Btw. nice work and THANKS!

**Comment by lozalojo** [comment]
All of these items are copyrighted, so there is no way the official system can include them.

The only items in CoC system are core skills (the ones most commonly used, nothing from DDT, Pulp or Now) and some example setups. These are at the packages directory and can be translated.

Take a look at my translation module and recreate it in german:

https://foundryvtt.com/packages/call-of-cthulhu-7th-babele-es/

But those packages would contain only a few example elements; to fully start playing CoC you have to create pc setups, archetypes, occupations, weapons, spells, monsters and roll tables for yourself based on the rulebook, the system fully support them, and then create a module compendium with all the items that you can activate in every CoC game.

**Comment by Barti-meaus** [comment]
Perfect, thanks. I just wanted to translate the core skills. Then I will recreate the translation module.

**Comment by lozalojo** [comment]
Great, close the issue if it is resolved, @Barti-meaus
