### ISSUE TITLE
Compatibility Issue with The Furnace (Module)

### ISSUE THREAD

**Issue by rnadams2** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#317]
Had a problem dragging Occupations onto a character sheet after the latest update. After fiddling with my activated modules, I found that disabling The Furnace ( https://github.com/kakaroto/fvtt-module-furnace ) fixed the issue. 

On an odd note, I have several Occupation items defined, and one of them actually worked with the module active. I couldn't find any difference between any of the items (beyond the actual content) that would make a difference. I had defined one Occupation after the CoC System update while the others were all built before; it was one of the previously built ones that worked. 

I was able to drag several Weapon items over with no issue. Also, the issue was present while using either version of the Character Sheet.

**Comment by HavlockV** [comment]
Sorry for taking time to tackle this.
This issue is resolved and will be available with the next release.
Thanks for the report.
