### ISSUE TITLE
[Feature] Add luck and sanity loss to NPC sheet to support Pulp cthulhu 

### ISSUE THREAD

**Issue by chekmx** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#322]
Cracking work,  thanks very much.  Some NPCs in published content (i.e. 2 headed serpent) have both lose of sanity and pulp talents.  The creature sheet does not show talent items when they are added.

**Comment by chekmx** [comment]
steps to recreate.
1. Create a new creature
2. Create a new talent
3. Drag the talent onto the creature sheet.

NB:  adding another item does not resolve this issue
versionsused  0.7.9 of Foundry and 0.4.7 of The Call of Cthuhlu 7th edition

**Comment by Vass1979** [comment]
Creatures DO NOT get pulp talentsrr

**Comment by chekmx** [comment]
In the two headed serpent campaign there are 4 main protagonist NPC that have both a sanity loss effect and pulp talents.   NPC sheets don't support san loss but do support talents.  Creature sheets support san loss but don't allow pulp talents.  It would be nice if there were an option to support this.  Also on page 130 of the Pulp Cthulhu book there is an example NPC that has pulp talents and a San Loss effect.

**Comment by kckaiwei** [comment]
I'm not familiar with Pulp Cthulhu, but I did take a look in 2 headed serpant to understand what you were looking at, and it does have them listed with talents.
