### ISSUE TITLE
[FEATURE REQUEST] Token Action HUD Support

### ISSUE THREAD

**Issue by drober76** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#324]
Consider adding support/integration for Token Action HUD.  The developer, Espositos, seems very open to collaboration and making the module accessible.  Allows players and GMs to make rolls without opening the character sheet.

https://github.com/espositos/fvtt-tokenactionhud

**Comment by snap01** [comment]
A pull request has been made for this https://github.com/Drental/fvtt-tokenactionhud/pull/209
