### ISSUE TITLE
[Feature] Add a Readme on using the system

### ISSUE THREAD

**Issue by kckaiwei** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#328]
As it stands, the readme is fairly sparse on how to use the system. For example I have no idea how to set a target when I roll and attack. It seems to default to a dummy. Realized a readme would be useful since I can't figure out how to apply damage to inflict a major wound in order disable major wound infliction when using pulp rules.

A proper readme, with some basic instructions would go quite a while for users and maintainers. It's hard to make changes when I'm having difficulty even knowing how some of the systems work from a user perspective.

**Comment by HavlockV** [comment]
Hi again.
That's somewhere in the futures plan.
The main issue is time. Some users (especially  @Viriato139ac#0342 on discord) have made good videos (in spanish) that demonstrate and explain how thinks are working.

**Comment by kckaiwei** [comment]
Unfortunately I'm not that great with spanish. :\ but I'll add him on discord and see if I can get some translations from him. I don't mind drafting out a readme on how some of this works, since it'll help future maintainers, and be pretty useful as the project expands.

**Comment by lozalojo** [comment]
Maybe a wiki for people to colaborate adding things?, dont know if there is enough community of CoC/Foundry for that.

@kckaiwei , does the subtitles youtube option work for my videos in spanish? I dont know, honestly.

**Comment by kckaiwei** [comment]
Is this one it?
https://www.youtube.com/watch?v=oHIm-XRhL4k

It doesn't show subtitles though. I do see like 3 english ones, which I'll watch when I have some free time and write some stuff down.

I'm not sure about building out a full wiki, but even some basic api, or structuring in a readme will go a long way for anyone who wants to add something, especially if someone's using the module and finds a bug during gameplay.

I suspect a lot of people who end up contributing will be like me, who have never worked on a foundry module before, and some documentation of basic structure would save them time reading the generalized foundry docs, and let them jump right in.

Also, there's no roadmap for features @HavlockV ? Should I just work on whatever issues look interesting/important?

**Comment by lozalojo** [comment]
Nope, it is in spanish, it is a series of 7 (for now) videos:

https://www.youtube.com/playlist?list=PLliKI08MgJaFu_x-U044rnmtJfT0d6rZA

When I spoke about wiki, was for users, not developers, to speak about CoC feautures from Keeper's perspective.

Roadmap is under "Future plans".

**Comment by dmt99** [comment]
You can turn on subtitles on the Spanish video and then turn on auto translate to English.  While not perfect it does give a reasonable indication as to what is being said.

There is also a set of videos by another used in English at https://www.youtube.com/watch?v=IJ5dLZDytGk that cover the basics pretty well.

**Comment by pconcepcion** [comment]
Another pull request #424 by @jantoniomartin is also relevant.

**Comment by pconcepcion** [comment]
I've added another pull request (#450) trying to mix all the documentation under one folder so it's easier to collaborate improving it.
