### ISSUE TITLE
Soucis de trad française sur la 0.4.7

### ISSUE THREAD

**Issue by vonv** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#329]
- les compétences ont du mal à se trier quand il y a des accents (crédit après crochetage)
- le daily loss de SAN n'est pas traduit
- on ne voit pas clairement quand une arme n'a pas de compétence de combat affectée

**Comment by HavlockV** [comment]
Merci pour le retour. Ce devrait être inclu dans la prochaine release.

**Comment by HavlockV** [comment]
Corrigé sur la branche develop
