### ISSUE TITLE
+DB doesn't seem to add the DB to the damage roll

### ISSUE THREAD

**Issue by jkb619** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#33]
created an 'item' called 'punch/kick'. set damage to 1d3, enabled "+DB", put on character sheet.  When clicking on it to roll, only rolls 1d3 (his bonus damage is 1d4)

**Comment by HavlockV** [comment]
Thanks for feedback, will have a look at it and correct it on next update

**Comment by HavlockV** [comment]
Corrected on 0.1.9. thanks for your feedback.
