### ISSUE TITLE
The occupations are in error.

### ISSUE THREAD

**Issue by rafarov** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#335]
The occupations are in error. When you put skills on them by dragging to a character sheet, she doesn't go and calculate occupational points.
I had tested it before I believe it was after the last update.

**Comment by HavlockV** [comment]
Hi Rafarov,
I was not able to reproduce the bug. Could you provide more background information ?
Also what addons do you have installed and is there any error message in the console (F12)

**Comment by rafarov** [comment]
I believe it is the error of incompatibility with the Furnace module.  I tested it now without this module and it worked.
But what happens is that when you have skills in the occupation.  The occupation is not placed on the character sheet when dragged.  Only educational points appear.  It also does not mark occupational skills.
But now I just tested it without Furnace and it worked fine.
I take this opportunity to congratulate you on the system on Foundry, it is incredible.  I did a translation of it by Babele into Brazilian Portuguese.  Keep it up and thank you for creating it.

**Comment by HavlockV** [comment]
Yes there's a compat issue with the furnace.
I've narrow it down to some renderTemplate calls. Didn't investigate further, but I think it may have something to do with some handlebar helpers or options defined by The Furnace.
When I'll find time I'll try to have a look at it.

**Comment by HavlockV** [comment]
Ok the issue actually came from a conflict on a property name. I changed the name of that property and it should be working with the furnace.
Will be available on next release.
Thanks for your report !
