### ISSUE TITLE
Dice so Nice can be seen by players when roll is private to GM

### ISSUE THREAD

**Issue by Mcgarnagle1** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#339]
As the GM, if you select any of the private, self, blind roll options, the animated dice for Dice So Nice still roll publicly on everyone's screen, showing the result there before they fade away. It does not produce a die roll chat card in the window, however.

It seems like this is specifically tied to dice rolls made directly from character sheets or NPC cards. I have Simple Dice Roller installed as well and the animated dice do not show up on players screens when it's private (but a chat card will display saying the GM has rolled some dice.

![image](https://user-images.githubusercontent.com/68829603/104402399-cf941b00-551b-11eb-8380-9f9a14456191.png)

**Comment by HavlockV** [comment]
Only player and GM can see the roll now.
