### ISSUE TITLE
[Feature] Block players skill editing

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#342]
Currently owner permission of an actor allows the player to unlock the padlock and edit skills values manually.

Other permissons (limited/observer) does not allow to unlock, but you cant roll any skill.

I'd change this so that only allow players to unlock the padlock when development is enabled or something similar.

**Comment by HavlockV** [comment]
Implemented on 0.5.0 :
* #342 Option added to allow/prevent players from unlocking sheets.
  * When unlocking is disabled for players, only keeper can unlock the sheet.
  * If the keeper unlock the sheet the player will see an unlocked sheet.
  * Upon exiting creation mode, all sheets get locked.
