### ISSUE TITLE
[Dev 0.4.8][Bug] No index for phobias/manias in settings

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#345]
No index for phobias/manias in the setting:
I've seen the key "BoutOfMadnessPhobiasIndexHint", but I havent found that setting and currently there is no autoroll on phobias table when a phobia is gained (the card shows you gain a phobia but it doesnt roll the table of sample phobias)

When you actually has reached the max loss from a creature, currently there is no message, the system asks for a roll and when you fail, the card ends without showing the san roll, so a message saying "Investigator cant lose more SAN from this creature" might help.

Maybe the message of "inmune" (inmune since you are in a bout of madness or inmune since you've lost the max san loss) might be at the begining of the SAN flow and not make the character roll for SAN when he cant lose more SAN and there is no other implication in the SAN roll.

**Comment by lozalojo** [comment]
The phobias/manias is not a bug, the table must include another table in the mania/phobia resullt in order to roll for that table.

So what it is not needed, then, is the setting that asks for phobia/mania tables:

![](https://i.ibb.co/sRFGHbF/screenshot-39.jpg)

I leave this issue open for the rest of suggestions

**Comment by HavlockV** [comment]
Setting removed
