### ISSUE TITLE
[Feature Request] Have an option to replace the stars with the actual degree of success on chat cards

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#349]
![screenshot 43](https://user-images.githubusercontent.com/470640/105495709-67300100-5cb4-11eb-841d-25fb4201cb67.jpg)

My players are used to seeing the degrees of success and the stars are confusing for them!

**Comment by lozalojo** [comment]
I would add: If only text (normal, hard, extreme, etc), use different backgrounds for different levels.
I would add even more: keep the stars/bugs, but add the text, there is enough space for both.

Just suggestions.

**Comment by HavlockV** [comment]
Implemented 0.4.8
