### ISSUE TITLE
Override for max hp value

### ISSUE THREAD

**Issue by jkb619** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#35]
In order to accomodate Pulp cthulhu, any way to have an override toggle for calculated fields?  (notably the HP max can't be changed..always reverts to the calculated value)

**Comment by HavlockV** [comment]
There is a mechanism like that on the NPC and Creatures, where you can deactivate the auto calculation (green/grey cog).
I will include it also for PC sheets in a future release.

**Comment by HavlockV** [comment]
Implemented in 0.1.9, click on the lock to unlock the pc sheet. A cog will show next to max hp/mp. Green = auto calculation, grey = manual override.
