### ISSUE TITLE
[Feature Request] Dark Ages features (armor and ranged weapons)

### ISSUE THREAD

**Issue by DouglasKims** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#359]
Two feature that would make Dark Ages games easier is:

**1- Armor dice rolls**; Dark Ages uses armor that uses dice rolls instead of fixed numbers. If you put the dice formula on the armor space it breaks the damage calculation and no damage is applied at all.

**2- Ranged/Thrown Weapons group**; Thrown weapons uses the melee skills for attacks, but ranged weapons only allows use of ranged skills, so lifting that restriction or finding a workaround would be good. Besides, it is a bit silly to classify bows, crossbows, slings and such as "firearms".

Thanks for all the work on this module, everything else I tested and used is working great! :D

**Comment by HavlockV** [comment]
Hi thanks for the suggestion.
0.5.3 : Armor can de defined as a roll string.
I'll work on the point 2 in a 'near' future.

**Comment by HavlockV** [comment]
In the meantime, for the second point, the name of the specialization is defined in the lang.json
Changing the value of keys "CoC7.SkillFirearm" and "CoC7.FirearmSpecializationName" to "Range" will give you a small workaround.
