### ISSUE TITLE
[BUG] Item description in character sheet is not showing

### ISSUE THREAD

**Issue by everyonecancode** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#361]
Foundry 0.7.9
CoC7 0.4.9

In "Gear & Cash" section of character sheet, items should show description of clicked item. Instead, nothing happens on screen and the exception is thrown:
`
item.js:579 Uncaught TypeError: Cannot create property 'value' on string '<p>Lorem ipsum</p>'
`

Reproduction:
1. Create new actor, "character" as a type
1. Press "padlock" icon, unlocking it
2. Got to "Gear & Cash" section
3. Click "Add item"
4. Create new item with name "Test" and add description: "Lorem ipsum"
5. Close item window
6. Click on "Test" item

Expected behavior:
A little dropdown should be created just below the item name, displaying item description

Actual result:
Nothing happens on screen. An exception is thrown in the console log.

**Comment by HavlockV** [comment]
Thanks for your feedback. It's a bug corrected on 5.0.
