### ISSUE TITLE
When player1 targets player2/ player cant click on dodge/fight back in chat.

### ISSUE THREAD

**Issue by MournerX** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#381]
When player1 targets player2/ player2 cant click on dodge/fight back in chat.
"User lacks permission to update chat messages..."

**Comment by Dick-K** [comment]
Can confirm...this only happens between players, not players and GM controlled NPCs. Using Foundry 0.7.9 and sheet 0.5.2.

**Comment by HavlockV** [comment]
It's a design flaw, one of the party needs to be de GM for this to work.
It will require a complete modification of the combat flow to fix.
In the meantime, the GM can solve the cards on behalf of the player.
