### ISSUE TITLE
[bug] roll requests

### ISSUE THREAD

**Issue by MournerX** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#382]
<img width="707" alt="Zrzut ekranu 2021-02-8 o 13 12 02" src="https://user-images.githubusercontent.com/12795659/107218146-83030900-6a0f-11eb-8d81-6645c8cfaf72.png">
Something wrong with request display -> attachement

**Comment by lozalojo** [comment]
Ops, I was the one that created that table and sent it to the repo, I see it correctly under 0.5.2:

![](https://i.ibb.co/fpXFstB/screenshot-50.jpg)

**Comment by MournerX** [comment]
Still same problem for me on 0.5.2 : code for roll request looks like: 

@coc7.check[type:attrib,name:Luck,difficulty:?,modifier:0,icon:fas fa-dice-d20]{ Luck (Blind)}

**Comment by MournerX** [comment]
Ok it seemed there is incopatibility with simple dice roller module.
