### ISSUE TITLE
[Bug?] Character sheet visibility on limited actor permissions

### ISSUE THREAD

**Issue by MagicSale** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#383]
Currently if a player  has "limited" permission on an actor, they are able to see all the stats of the sheet.

However, on limited permission they should only see basic information like Name, Age, Image etc., not the stats, inventory , backstory or attacks.

**Comment by joaovscorreia** [comment]
@MagicSale, this issue was resolved in the latest system version 0.6.3. If you are still having this problem, please let us know.
