### ISSUE TITLE
[Bug?] Targetted Skill Roll Request Sent to All Players

### ISSUE THREAD

**Issue by Dick-K** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#384]
As GM, if I have 2 players, and select one and then Ctrl-Click on a skill on their sheet, the skill check card with that Actor's name is sent to all players. All players can then click for a skill check.

As GM I have Private GM Roll set, as do the players.

I guess the preferred behaviour is to only send the clickable check request to the targetted player, with just a notification of the request to other players depending on whether the GM has Private GM or Public rolls set.

**Comment by joaovscorreia** [comment]
@Dick-K, I'm closing this Issue as this has (possibly) already been resolved. If this still persists please open it again!
