### ISSUE TITLE
[Bug] Top Attribute Section of NPC and Creature Sheets Do Not Display Correct Typeface

### ISSUE THREAD

**Issue by Dick-K** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#386]
The top attribute section of NPC and Creature Sheets do not display the typefaces set in the sheet config until a PC sheet is first displayed. After any PC sheet is displayed, the typefaces are correct for the remainder of that Foundry session.

**Example Creature Sheet**

**With No PC Sheet Displayed**
![image](https://user-images.githubusercontent.com/73724728/107566195-7d0e5300-6bdc-11eb-95be-ac03048cc793.png)

**After PC Sheet Is Displayed**
![image](https://user-images.githubusercontent.com/73724728/107566572-f3ab5080-6bdc-11eb-8b30-7937aa46dda8.png)

**Comment by joaovscorreia** [comment]
@Dick-K, I can't reproduce this bug, so I believe it's already been resolved. If it's still happening to you, let me know!

**Comment by Dick-K** [comment]
Hi Castanho, yes, thanks for all the hard work, that's resolved fine now.
