### ISSUE TITLE
[Feature] Houserule for opposed rolls

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#387]
<h1>Problem:</h1>

The mechanism for opposed rolls state than on a tie result, the one with the highest skill wins.
This is a graph of an opposed roll, x=active skill, y=passive skill, z=probability that active wins
![](https://i.ibb.co/N29hkWc/newplot.jpg)
The problem here is the big step that is seen in the middle, what it means is that a guy with 86% (active) vs a guy with 85% wins 63,5% of all the opposed rolls
But a guy with 85% vs a guy with 86% wins only 34,7%
Both x,y points are close in the graph (85,86) (86,85), and probabilities are way different, this is why there is a big step, from 86vs85 next to 85vs86.
Moreover, the differences in probabilities are greater as the skills are higher (the step increases)
Logic says that a 85Vs86 and 86vs85 both should be around 50% chance of winning, both contendents have similar level of skill, there shouldnt be such a difference between chances of winning between one or the other, both might be similar, and similar to 40 or 45%, considering there is a chance that both fail their rolls and no one wins.

<h1>Solution:</h1>

[House rule] Alternative opposed rolls mechanism: on a tie result, the one that rolled a higher value wins.

This is the resulting graph:
![](https://i.ibb.co/PT7qy8d/newplot-1.jpg)
Now, there are no big steps and similar skills have similar chances of winning that tends to 50% as the skills are close to 100% and there is no chance of both failing their rolls.

**Comment by joaovscorreia** [comment]
@lozalojo, nice job with this. Is this referring to the "opposed rolls Viriato139ac tie breaker"? Has it already been resolved?

**Comment by lozalojo** [comment]
> @lozalojo, nice job with this. Is this referring to the "opposed rolls Viriato139ac tie breaker"? Has it already been resolved?

Yes, Veterini added a tickmark at system options called "alternative opposed rolls (by Viriato139ac)" or something similar.

I close the issue, @castanhocorreia
