### ISSUE TITLE
Imcompatibility with MEME

### ISSUE THREAD

**Issue by vonv** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#389]
Using https://foundryvtt.com/packages/markdown-editor/ which is a great module to right Jounral entries clearly and with no HTML overload, it's not compatible with shortcut to send dice roll: 

- it doesn't work with: @coc7.check[type:skill,name:Baratin,difficulty:1,modifier:0]{ baratin}
- but it works well with: @JournalEntry[qPw9igfiuHgEul16]{Crossman}

**Comment by joaovscorreia** [comment]
@vonv, are you still having this issue on the current version of the system (0.6.1)?

**Comment by vonv** [comment]
Yes, nice, all work well. Thank you.
