### ISSUE TITLE
Other fonts compatibility of the investigtor sheet v2 during creation/evolution stage

### ISSUE THREAD

**Issue by vonv** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#390]
The width of the skills cells during creation/evolution stage is fixed (22px), so, when you chose a marvelous new font, it may result in the basis % not showing well: 2... for 20 for example.

**Comment by HavlockV** [comment]
Hi Vonv, thanks for the feedback.
Many thing have been changed from fixed px size to rem on 0.5.3. This should, I hope, solve that issue and improve the look and feel of the sheet.

**Comment by vonv** [comment]
Je vais pointer sur la branche develop pour voir tous ces commit !
Merci de ton travail Vétérini ! :)

Vonv

2 mars 2021 13:34 "HavlockV" <notifications@github.com (mailto:notifications@github.com?to=%22HavlockV%22%20<notifications@github.com>)> a écrit:
	Hi Vonv, thanks for the feedback.
Many thing have been changed from fixed px size to rem on 0.5.3. This should solve that issue and improve the look and feel of the sheet.
	*

**Comment by vonv** [comment]
Thanks !
