### ISSUE TITLE
Getting spell info

### ISSUE THREAD

**Issue by jantoniomartin** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#396]
I have some doubts about how a spell item is meant to be used:

First I create a spell and I fill stats like casting time or cost. Then, I drag the spell into a sheet's inventory. If I click the spell icon in the inventory, nothing happens (it doesn't appear in the chat or anything). If I click the spell name in the inventory, I can see the spell description but not its cost or casting time. The only way to see these stats seem to be by editing the spell.

Is this the intended behaviour or is it something still not developed? Am I missing some step?

Thanks a lot for this awesome module!

**Comment by joaovscorreia** [comment]
It's supposed to be that way, @jantoniomartin, but there are definitely future plans to improve the systematics for all Items.
