### ISSUE TITLE
font size too small

### ISSUE THREAD

**Issue by zeteticl** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#398]
![image](https://user-images.githubusercontent.com/23254376/108680248-955d6680-7528-11eb-9632-e2041e03c85f.png)

for other language, the font size is too small.
how can i change bigger?
i have edit css files. but no effect

**Comment by HavlockV** [comment]
Hi zeteticl. Thanks for the feedback. A few improvement have been made to change many size from px to rem. They will be released on 5.3
In the meantime you can try in the system options to check the "Override Sheet Artwork" box. Restart an go back to options. There you'll see a new input "Default font size (px)". It's 16 by default, you can increase it at will.
