### ISSUE TITLE
Suggestion: random luck when using points system

### ISSUE THREAD

**Issue by jantoniomartin** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#401]
The point buying system in CoC shares 460 points among the eight characteristics, not including Luck. It seems that Luck is intended to be randomly generated even when using this system.
Maybe the Luck input box could be disabled or hidden when a point buying setup is chosen and, when dropping the setup into the character sheet, Luck could be randomly generated.

**Comment by HavlockV** [comment]
Issue addressed. It will be part of the next release.
Thanks for your help !!!
