### ISSUE TITLE
[Bug] Opposed Roll Fails to Use Current Token Image for Wildcard Tokens

### ISSUE THREAD

**Issue by Dick-K** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#415]
If a token that has been created from a prototype that uses the wildcard token image mechanism, the opposed roll displays  the token name and the broken image icon instead.

The opposed roll works great apart from the image issue.

**Comment by HavlockV** [comment]
Thank for the feedback.
What do you call wildcard token ?

**Comment by Dick-K** [comment]
It's the wildcard feature on the image tab of the token dialogue.

![image](https://user-images.githubusercontent.com/73724728/111192941-890d7c00-85b1-11eb-9976-89cce70ca5a0.png)
