### ISSUE TITLE
Rolling a dice with the new icon tool doesn't use personal colour choice (Dice So Nice)

### ISSUE THREAD

**Issue by vonv** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#420]
![PrtScr capture](https://user-images.githubusercontent.com/44206935/111217828-48742980-85d6-11eb-9421-298dffa09294.jpg)

With module Dice So Nice

**Comment by jantoniomartin** [comment]
It seems that this module doesn't use DsN colors unless you configure empty values in the DsN related system settings:

![coc-settings](https://user-images.githubusercontent.com/439759/111525128-86e82080-875d-11eb-869b-9b91dc6ebd6f.png)

This is valid also for rolls made from the character sheets.

**Comment by vonv** [comment]
You're right ! Thanks !
Tested and approved :)
