### ISSUE TITLE
[Please Ignore] Skill Addition to NPC or Creature after Initial Creation Does Not Initialise Base Value

### ISSUE THREAD

**Issue by Dick-K** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#421]
Using 0.5.4

Dragging a skill from _Items_ to an NPC or Creature after initial creation does not initialise the base percentage value. This has to be set from the sheet after the skill is dragged onto it.

![image](https://user-images.githubusercontent.com/73724728/111221636-a9016780-85d2-11eb-8bd4-f4b2124ae432.png)

**Comment by jantoniomartin** [comment]
I tried to reproduce this error, and I couldn't. It works fine for me. Could you provide more information?

**Comment by Dick-K** [comment]
I did a bit more testing.
All modules OFF.

 If I double-click the actor and drag skills onto the prototype token sheet, it works fine. If I drag the actor to the map, double-click the token and add the skill to the token sheet, _if the token is not linked to the actor_, the skill base is either blank or as in one case, where the skill base was 1%, '-1'.

If the token is linked to the actor, the skill base is displayed correctly when dragged from a Skill item.

In addition, if I switch to 'Linked' the missing values may appear, but I also get odd behaviour switching between 'Linked and 'Not Linked' where some skills will disappear but reappear if the token is 'Linked' again.

**Comment by Dick-K** [comment]
Thinking about it, this may be the correct 'undefined' behaviour. Linking and Unlinking while adding skills in either state definitely has the hallmarks of an edge case to me. I should simply plan better.

**Comment by Dick-K** [comment]
It's probably appropriate to close this, thanks for replying though.
