### ISSUE TITLE
"1920 Character" missing some skills that are on the 1920s character sheet

### ISSUE THREAD

**Issue by anthonyronda** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#43]
Missing skills from the compendium template that are on the CoC 1920s character sheet

Archaeology (01)
Swim (20)
Throw (20)
Track (10)

Also, I'm not sure how you want to treat the general versions of the specialize-able skills. Pilot and Survival are there, but Art/Craft, Language (Other), Science, were skipped over

**Comment by HavlockV** [comment]
Thanks for your feedback. I'll add the skills to the default sheet on the next release.
In the meantime, the skills can be added 'on the fly' directly in the PC sheet. Click on the lock to enter the sheet in edit mode. On the skill tab you'll have a + icon which will allow you to add a new skill. It can also be created from foundry's Items Directory and drag onto the sheet.
"Specialize-able" skills are just cosmetic for the time being. For example you can create a skill called 'R’lyehian' flag it as Specialization in the corresponding skill sheet and fill the specialization text box with 'Old gods language'. It will display on the sheet as  "Old gods language(R’lyehian)"  and be sorted according to the 'mother skill' name.
The complexity level to handle it differently is too high in regard to the gain to be implemented now. It will be in a distant future, only Yog-Sothoth knows when.

**Comment by HavlockV** [comment]
Skills added to the CoC 1920s character sheet.
Thanks for your feedback.
