### ISSUE TITLE
Customizable backgrounds for character sheet with a template PSD for users to make their own

### ISSUE THREAD

**Issue by apoapostolov** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#435]
This would allow creators and DM to make their own backgrounds for character sheets for other eras or subgenre books (i.e. Dark Ages, Invictus, etc.) The background could be a compendium object that contains URL to a background and little else, and can be applied to a charsheet by dragging it or by setting it somehow. It doesn't change anything else and is not shown on a field, but changes the background of the character sheet made of this object.

**Comment by HavlockV** [comment]
Welcome back. 
Thanks for the suggestion. There's already something in the system's options to customize the character sheet.
To enable it, tick 'override sheet artwork' option in system's options.
Refresh your client and new options will be visible to change :
- the sheet background
- the sheet image (that blue tentacule on the top left corner)
- the sheet fonts
- the font size
- the colors used
This works only for PC sheet at the moment.
There's also a 'bug' that will be addressed soon where the style is applied only after you open one character sheet.
This works only for sheet V2 (you can select that from the sheet config).
I don't know if this is what you're looking for. If not, let me know.

**Comment by apoapostolov** [comment]
Thank you I had no idea this was already available!!
