### ISSUE TITLE
[Feature Request] Damage/Weapon Type vulnerability for Monsters

### ISSUE THREAD

**Issue by MournerX** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#445]
Hi,

Feature sugestion adding rules for HP loss vulnerability for Monster.
i.e Monster Can be immune to some weapon types but vulnerable to other, or hurt only by <type>, or all dmg from all types =1 except type holy. and so on. 

With this another feature is to add input variable for setting this type of weapon i.e. normal, holy, explosive etc. that you could use with vulnerability rule.

Was trying to add some monsters from Down Darker Trails and most have special rules concerning damage. 

Best regards,

**Comment by lozalojo** [comment]
Duplicated: https://github.com/HavlockV/CoC7-FoundryVTT/issues/274
