### ISSUE TITLE
When localization is applied, money informations are not automatically updated based on credit rating

### ISSUE THREAD

**Issue by timpatim** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#452]
Tested with french language, version 0.5.4, FVTT version 0.7.9.

When french language is selected in game's options, various fields are translated. "Credit Rating" becomes "Crédit". 
Game system seems to fail finding credit rating skill as money informations (spending level, cash, assets...) are no more correctly computed. I believe this is due because the skill is found based on his label which is not the same after being translated.

**Comment by joaovscorreia** [comment]
@timpatim, are you still having this issue with the new version of the system (0.6.1)?

**Comment by timpatim** [comment]
I don't since we play in English now. I will check this evening after work
(it's morning).
