### ISSUE TITLE
Custom Sanity Check not working as expected when SanMin=0

### ISSUE THREAD

**Issue by Gorvaine** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#458]
Custom Sanity Checks from the character sheet works ( Control + Alt + Sanity ) works as expected when (SanMin > 0).

If SanMin = 0 then
  when the character clicks on the chatbutton, a dice is rolled without any feedback. You just see the 3d dice rolling.
  if Sanity Check Pass then
    You see nothing. No feedback at all.
  If Sanity Check Fails then
    You see the roll result on the chat card with a button to drop the Sanity, or the button to roll the sanity loss die.

I did not test whan happens if you use SanMax=0.

Expected:

Same feedback on the chatmessage when you use SanMin >0 and SanMin = 0.

I hope the message is clear. I didn't know how to explain it. If it's not clear yet, I can make a little video.

**Comment by Astavie** [comment]
I'm getting the same issue

![image](https://user-images.githubusercontent.com/7745457/120891054-c6106a00-c606-11eb-82cd-7c4a4bc358a5.png)

I pressed the button, some dice were rolled but there is no feedback
this only happens when the minimum sanity is 0
