### ISSUE TITLE
[Bug] Items in the Gear and Cash section have "undefined" descriptions when clicked on

### ISSUE THREAD

**Issue by claycle** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#460]
Although Books, Spells, and Statuses will display their defined descriptions when clicked on in the Gear & Cash tab, clicking on an Item, whether created in the tab using the Add Item button or dragged in from an established item card. only presents an undefined error.

See attached screenshots for examples:
<img width="551" alt="Screen Shot 2021-04-08 at 11 22 03 AM" src="https://user-images.githubusercontent.com/419840/114062088-bc63c380-985c-11eb-9ec5-482534a19896.png">

**Comment by claycle** [comment]
Content that should be displayed from the items:

<img width="865" alt="Screen Shot 2021-04-08 at 11 24 04 AM" src="https://user-images.githubusercontent.com/419840/114062362-0ba9f400-985d-11eb-934c-63a33b41f744.png">

**Comment by Dick-K** [comment]
If I may add something here, attempting to update the _Weight_ of an existing item appears blocked but sends a message "Hello World" to chat.

**Comment by HavlockV** [comment]
Item sheets are..... in need of some love (Totally ugly)
Thanks for the report, it's corrected now. It will be pushed with the next release.
@Dick-K Regarding that "Hello World" message I wasn't able to reproduce it. Could you provide more background ?

**Comment by Dick-K** [comment]
> @Dick-K Regarding that "Hello World" message I wasn't able to reproduce it. Could you provide more background ?

This must have been a passing glitch, I can't reproduce it now, either. Apologies, ignore this. If it happens again I'll do some more investigation. Thanks for keeping on top of things
