### ISSUE TITLE
[Feature] Implement dragndrop attack on tokens

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#461]
Is it possible to implement dragndroping and attack over a token to initialize the combat flow? It would be a cool enhancement, dont know if it will take a lot of work to implement, but this code is taken from swade, it might be useful maybe (code from JuanV from discord):

```Hooks.on('dropCanvasData', (canvas, item) => {    
    let grid_size = canvas.scene.data.grid
    canvas.tokens.targetObjects({
        x: item.x-grid_size/2,
        y: item.y-grid_size/2,
        height: grid_size,
        width: grid_size
    }); 
    $("[data-item-id^='" + item.data._id + "']").last()[0].children[0].children[0].click()
});```

**Comment by HavlockV** [comment]
I have been looking into this for a time now. Thanks for that, I will have a look at it. I think it may be not too difficult. My issue was exactly this, determining which token was being attacked.
