### ISSUE TITLE
[Feature][Localization] Implementing German Localization + Additional

### ISSUE THREAD

**Issue by nilsriesenberg** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#468]
For my round I created almost all of the skills and subskills being present in the basic keepers rule book.
My work includes up until now:
- premade Character with all skills being present in the keepers handbook
- all skills and specialisations
  - enhanced explanation of the skill
  - copied orignal text from the keepers rule book
  - crossreferences to other skills being named
  - direct automatic dice rolling in the entry
  - crossreference to a table explaning the different percentages and which skill level they refer to
  - location of the skill/entry in the keepers rule book
- automatic randomized table which lets players roll a randomized background
- automatic randomized tables (taken from keepers rule book)
  - bouts of madness as summary
  - bouts of madness while playing
  - table of 100 phobias
  - table of 100 manias

How can I help to include this in the CoC package?
<img width="1168" alt="Bildschirmfoto 2021-04-13 um 15 30 27" src="https://user-images.githubusercontent.com/16704058/114561152-99c31780-9c6d-11eb-962c-e914013482a9.png">
<img width="692" alt="Bildschirmfoto 2021-04-13 um 16 01 38" src="https://user-images.githubusercontent.com/16704058/114565463-93369f00-9c71-11eb-947b-d2d2f60ed942.png">
<img width="890" alt="Bildschirmfoto 2021-04-13 um 15 30 49" src="https://user-images.githubusercontent.com/16704058/114561146-9891ea80-9c6d-11eb-915c-8ad3bda1bc1a.png">
<img width="898" alt="Bildschirmfoto 2021-04-13 um 15 31 37" src="https://user-images.githubusercontent.com/16704058/114561138-9760bd80-9c6d-11eb-8bea-36b1377c8d90.png">

**Comment by lozalojo** [comment]
You cant, it is copyrighted content, you cant distribute it freely without the german publisher permission.

Also, I've seen you've reworked the deuscht localization file, maybe you might want to collaborate with this project too:

https://github.com/Xithrim/call-of-cthulhu-7th-babele-de

**Comment by nilsriesenberg** [comment]
@lozalojo Sadly. I will ask the german publisher. 
Ulisses Games uploaded an Offical Version of ["Das Schwarze Auge"](https://foundryvtt.com/packages/dsa5/) to FoundryVTT so I think the german publisher Pegasus will also have an interest in being available on FoundryVTT.
I think until then there could be a workaround until a offical Implementation.
For example the module "Plutonium" for D&D 5e is also available on FoundryVTT allthough they don't endorse it. And [Plutonium](https://5e.tools/plutonium.html) offers community sourced content.

Reagrding the translation project: I'll look into it. Maybe i can help you out 👍

**Comment by lozalojo** [comment]
How FoundryVTT would support a platform like Plutonium which hosts pirated stuff?

**Comment by HavlockV** [comment]
Hey @nilsriesenberg.
Unfortunately, as mentioned by @lozalojo I can't release any copyrighted material with the system. That's the deal from day 1 with foundry staff, unless we get official approval from the publisher (Chaosium).
We contacted some publisher of localized version on CoC and their answer was always the same. They are fully on board to bring the content to Foundry but they can't do it without Chaosium approval. So it's on hold for the time being awaiting an approval from Chaosium (MoB). If you get in touch with the german Publisher and ask him to contact Chaosium for this, it may help.
Regarding the compendiums, the actual trend is to release them as module for the system (Without any text unfortunatly).
I received our PR for the core translation, it will be released with the next upgrade, thanks for your participation !

**Comment by nilsriesenberg** [comment]
Ok, sucks to hear but I hope Chaosium changes their mind. Releasing the compendiums would be helpful. I mean the real value lays in the adventures anyway. I'll contact pegasus and ask. maybe it helps. 🤷
Thanks for the clarification to both of you!

**Comment by HavlockV** [comment]
I think Chaosium invested some money i roll20, and might not be very eager to see foundry gaining momentum.
Just a speculation.

**Comment by SepSepone** [comment]
Danke für deine bisherige Übersetzungsarbeit. Es hilft bei Spielern mit wenig Englischkenntnissen bestimmt enorm, wenn zumindest ein guter Teil des Charakterbogens auf deutsch ist. Kann dir gar nicht genug danken, Foundry ist ein geniales VTT, aber der Mangel an vorgefertigtem Inhalt hilft nicht gerade beim Vorbereiten. Alles Gute und bleib gesund.
