### ISSUE TITLE
[Suggestion] create action which imports missing lines from the en file into the other language files

### ISSUE THREAD

**Issue by nilsriesenberg** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#478]
My suggestion would be to create an action which imports all newly added lines of the en language file into the other language files and also notifies the contributors about it. That would make the translation workflow much easier.

**Comment by joaovscorreia** [comment]
@nilsriesenberg, what you suggested seems a bit much. However, we made an attempt to make life easier for translators, take a look: https://github.com/HavlockV/CoC7-FoundryVTT/blob/develop/.github/TRANSLATIONS.md
