### ISSUE TITLE
[BUG] CTRL-Left Click Behavior is Inconsistent Depending on Link Source

### ISSUE THREAD

**Issue by claycle** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#479]
Skill check requests (via links) behave differently depending on where the request is generated from.

Note: In the example below, Operate Heavy Machinery is meant as a placeholder for any linkable skill or attribute check.

**Behavior #1 (Normal):**

1. Select and target token on the scene.
2. Open a Journal entry, with a skill check link in the text, eg, @coc7.check[type:skill,name:Op. H. Machine,difficulty:0,modifier:0,icon:fas fa-snowplow]{ Op. H. Machine}
3. CTRL-Leftclick the journal entry link.
4. The Player controlling the selected token will be whispered "Your keeper is requesting a Operate Heavy Machinery check".

![CoC Behavior 1](https://user-images.githubusercontent.com/419840/115411094-ce2c5b80-a1b8-11eb-9363-7797a0758465.jpg)

**Behavior #2 (Inconsistent with Behavior #1):**

1. Select and target token on the scene. Double-click the targeted token to open the target's character sheet.
2. CTRL-Leftclick the Operate Heavy Machinery skill on the target's sheet.
3. The targeted token announces to public chat, as if speaking in character, "Your keeper is requesting a Operate Heavy Machinery check. **This is inconsistent behavior.**

![CoC Behavior 2 Inconsistent](https://user-images.githubusercontent.com/419840/115411166-dbe1e100-a1b8-11eb-970d-744c43fe362f.jpg)

**Suggested Behavior #2 Fix:**

Behaviors 1 and 2 should be nearly identical (ie, the use of CTRL-Leftclick upon any skill link, regardless of source, should generate a whisper to the targeted token to make the clicked skill roll).

Therefore, Behavior 2 should be:

1. Select and target a token on the scene. Double-click the targeted token to open the target's character sheet.
2. CTRL-Leftclick the Operate Heavy Machinery skill on the character sheet.
3. The player controlling the targeted token will be whispered "The Keeper is requesting a Operate Heavy Machinery check."

![CoC Behavior 2 Fixed](https://user-images.githubusercontent.com/419840/115411215-e7350c80-a1b8-11eb-932b-9d32e9288e04.jpg)

Furthermore, it should not be necessary to target the token at all, as performing such a click on a character sheet necessarily implies that the GM wants *that character* to make the roll.

Thus, Behavior 2, Optimal:

1. Open a character sheet.
2. CTRL-Leftclick the Operate Heavy Machinery skill on the character sheet.
3. The player controlling the **character sheet** will be whispered "The Keeper is requesting a Operate Heavy Machinery check."

![CoC Behavior 2 Fixed Optimal](https://user-images.githubusercontent.com/419840/115411281-f3b96500-a1b8-11eb-8c91-c63f71b15cb4.jpg)

**Comment by joaovscorreia** [comment]
@claycle, are you still having this issue on the current version of the system (0.6.1)?

**Comment by claycle** [comment]
I think Vent added the new CTRL-click-to-create-link behavior as an orthogonal response to this inconsistency. It does not solve the basic issue directly (it still exists), but it does provide a work-around.
