### ISSUE TITLE
[Suggestion] show roll title in backup

### ISSUE THREAD

**Issue by zeteticl** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#481]
when fvtt backup the chat log to txt, it wont show the roll title.
and the format is hard to read, hope it have the way to improve…

![image](https://user-images.githubusercontent.com/23254376/115507809-2ba2d400-a2af-11eb-8ec3-70b65a676c67.png)

[4/21/2021, 2:34:12 PM] Peter
1 tens dice
0																				0
1 units die
1																			1
Critical success, regular success required.
1

**Comment by snap01** [comment]
The output file is generated by FoundryVTT.

Currently the check messages do not have dice assigned to them so FoundryVTT does not include that text.

The next release will mark newly rolled checks as having dice assigned to them.
