### ISSUE TITLE
[Bug][Feature Suggestion] Clicking Links on Owned Character Sheet Should Override Foundry Token Selection Behavior for Rolls

### ISSUE THREAD

**Issue by claycle** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#493]
This is related to issue https://github.com/HavlockV/CoC7-FoundryVTT/issues/479, but a more general application.

When a GM or player clicks a link on an owned character sheet, the "speaker" of the roll and the character for whom the roll should always apply (in the case of directing roll requests to the proper player) should be the character (player) to whom the character sheet belongs. Default Foundry behavior is to have the speaker (target of roll) be the selected (or targeted?) token in the scene.

Unlike links embedded in journals or other items which have no explicit relationship to characters or players, links on owned character sheets (**particularly** player-owned sheets) are special in that they explicitly tie a particular player, character sheet, and token together. Likewise, similar information can be inferred for "major" NPC characters (GM, character sheet, and token explicitly tied together). "Mob" NPCs - many tokens to one one NPC sheet relationships - represent a case in which the default Foundry behavior works (ie, it is not possible to determine who the "source" of the roll request is from the character sheet because there is not a 1-to-1 relationship between the sheet and tokens in the scene - it is therefore necessary to manually select tokens in scene to identify the speaking/rolling character).

Foundry's default behavior does not correctly mimic real-world use cases for the explicit cases. In the real world, the GM would not pick up Allen's character sheet, point to a skill on it, and expect Bob's character to make the roll. Implicitly, if the GM points to a particularly character's sheet (Allen), they expect that player/character (Allen, not Bob) to make the roll. If the GM wants Bob to make a roll, they would point to Bob's sheet and skills.

It should not require holding down option, control, shift, or some combination of meta-keys to make this behavior occur. It is implicit and clear, from the fact that the GM has opened a PCs sheet, that the intent is that the GM intends for that PC to be the target of the subsequent roll requests.

### Cases for Using Selected or Targeted Tokens

**Selected Token(s) as the Speaker or Roll Target:** If the GM opens an unowned character sheet (as a template, for example) and clicks a skill for a roll, then the selected token(s) in the scene can inform the game system what tokens should speak or be the roll targets.

**Targeted Tokens**: If the GM opens an _owned_ sheet and has a token *targetted* in the scene, there is a need to differentiate between a simple and opposed roll (with the selected token as the implicit opposition). In this case, a meta-key should inform the system whether the roll is simple or opposed, and act accordingly (ie, open an opposed roll card and fill in both sides of the opposition roll automatically). If the sheet is unowned and the targeted token is also selected, then the system should direct a simple roll to the selected and targeted token. If the targeted token is not selected, the system can assume that the GM wants to begin an opposed roll against the targeted token, open an opposed roll card, and wait for further input (similar to the behavior currently).

**Comment by joaovscorreia** [comment]
@claycle, I'm closing this Issue as this has already been resolved. If this still persists please open it again!
