### ISSUE TITLE
[Request] Rationalise tiling of main sheet background

### ISSUE THREAD

**Issue by Dick-K** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#508]
If I place an image as the backgound for the main sheet, regardless of its size, smaller or larger than the initial size of the sheet, and regardless of any trailing 'repeat <n>' parameter, including omitting the parameter, the resulting background always has some tiling artifacts.

Is it possible to simply fit the indicated image to the sheet window, stretching or shrinking it as necessary?

![image](https://user-images.githubusercontent.com/73724728/117583886-8f2b5f00-b101-11eb-958a-24747835adbd.png)

**Comment by HavlockV** [comment]
Thanks for your suggestion.
A setting is added in develop to address this.
Image were initially designed as border-image and sliced to preserve the header size.
In the new options you can now override it and use tile and access the background and background-size properties.
To activate this select the background type in the options :
- slice = border-image with the slice (default)
- auto/contains/cover = background with corresponding size.

**Comment by Dick-K** [comment]
That's great, thanks Veterini. I'll have a look at this when I upgrade to the new version.
