### ISSUE TITLE
Actor portrait duplication with Chat Portrait module active (but only when targeted by an attack)

### ISSUE THREAD

**Issue by anthonyronda** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#51]
![image](https://user-images.githubusercontent.com/1410433/87956527-2644fe80-ca7d-11ea-9318-4949c02d4526.png)

I have no expectations of having perfect compatibility with any third party modules, but this is a behavior I ran into that I thought you might want to consider.I understand that having the actor portrait there is helpful to see who the attacker is targeting.

I have an image for the dodge "weapon" (as shown in the last chat card). It's just a crappy free icon but I felt as though it should be shown in this case.

My suggestion for showing the targeted actor's portrait is as shown below:
![image](https://user-images.githubusercontent.com/1410433/87957408-38736c80-ca7e-11ea-9c3a-bb5e5d81cc87.png)

**Comment by anthonyronda** [comment]
Upon further playing around with it, I now see that a Dodge "weapon" that uses the Dodge skill is no longer a necessary part of the combat flow in 0.2.x. My suggestion still stands, though I realize now that displaying a skill/weapon icon the defender's chat card isn't easy

**Comment by HavlockV** [comment]
Hi Roondaa,

Thanks for the feedback.
As you mention, the dodge weapon is not necessary. You need to have a Dodge skill.
Skills are identified by their name, so It has to be called Dodge and spelled correctly with the correct capital letter for the system to be able to find it.
In the last version the  name of the skill is in the language file under "CoC7.dodgeSkillName" entry, therefor can be 'localized'.
For the icon's target that shouldn't be difficult to do. I'll try to have it ready for the next iteration.

**Comment by anthonyronda** [comment]
I'm using Foundry on a secondary machine while visiting family, so please excuse the placeholder images
![image](https://user-images.githubusercontent.com/1410433/90283012-665d8e00-de3d-11ea-8164-f85175abeb17.png)

I think your solution to add the target to the combat chat card is great! But my reason for the original issue is that the Actor portrait is duplicated here while using the Chat Portrait module (I mistakenly called it Chat Images originally).

I like having Chat Portraits for every chat card (including the Listen roll shown above and player text chats).

If you think you just want to see the Actor portrait on the combat card, could you have the system check for the Chat Portrait module, and remove the duplication if Chat Portrait is active?

Another option could be to show the Actor Portrait on every chat card, not just the combat card. In that case I would be happy to just deactivate the Chat Portrait module

**Comment by HavlockV** [comment]
I misunderstood the issue. My bad. I will check that module and try to reproduce the bug.

**Comment by HavlockV** [comment]
I disabled my chat portrait for the time being. Chat Portrait is doing a good job.
I implemented most of the 'in card' portraits and icons.
This is pushed on the develop branch.

**Comment by HavlockV** [comment]
Available on master as 0.2.8
