### ISSUE TITLE
PDFoundry Integration

### ISSUE THREAD

**Issue by Mcgarnagle1** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#52]
Hey HavlockV,

Any chance that you'll consider adding PDFoundry Integration into your CoC7 system? 

https://github.com/Djphoenix719/PDFoundry

**Comment by HavlockV** [comment]
Thanks for the suggestion, will be included in the next push

**Comment by HavlockV** [comment]
PDFoundry is integrated in 0.2.3
Thanks for your suggestion.
