### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by heliobolseiro** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#536]
Suggestion:
-As in the fantasy grounds, I could put a notice notifying how many lucky points a certain researcher needs to spend in order to succeed in a test. And also, a button in the chat for him to trigger, in case he wants to spend his luck (which would be automatically deducted from the card). I don't know if it is too complex to do that, but it would be perfect.
- Another suggestion is to enable players / guardians to mark targets directly on the combat tracker. There are many sessions of cthulhu that we ended up not using tokens, and in the end it forces to place some tokens just for combat control.
- and was that bug seen when players try to dodge, etc ... in the chat in a fight?.

**Comment by Vass1979** [comment]
Luck spend is already there

**Comment by pconcepcion** [comment]
@heliobolseiro to be able to spend the luck points the player has to click on the result to show the details and there it will show the extra options, including spending luck.
