### ISSUE TITLE
Localizable skill and item names in compedium

### ISSUE THREAD

**Issue by RedwanFox** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#541]
subj.

Right now I can only replace names in existing databases for my players, and on the first system update translation will break.

**Comment by snap01** [comment]
I do not believe FoundryVTT supports localization of compendiums, there is a module called "Babele" which adds this feature.

Searching for "Call of Cthulhu" under Add-on Modules should show the languages already available as translated compendiums.
