### ISSUE TITLE
Skill specializations display full names in character sheet sometimes

### ISSUE THREAD

**Issue by Astavie** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#575]
![image](https://user-images.githubusercontent.com/7745457/121164460-e4b57180-c84f-11eb-88ae-2e8fee684815.png)

When adding a skill specialization to a character sheet, the full name of that specialization, in the format `skill (specialization)`, is shown under the skill category. This leads to cut off text.

![image](https://user-images.githubusercontent.com/7745457/121164591-f72fab00-c84f-11eb-9494-416e723b2c9c.png)

**Comment by PhilMC157** [comment]
What you can try is: Configure Settings --> System Settings --> scroll down, uncheck "Limit skill name length"
