### ISSUE TITLE
[BUG] Cant import prototype bar 1,2 attribute

### ISSUE THREAD

**Issue by zeteticl** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#578]
If I set character prototype bar 1,2 attribute to hp, san and export to json,
after i import the json file. 
bar 1,2 attribute would change to none. 

![image](https://user-images.githubusercontent.com/23254376/121305233-f110fb80-c92f-11eb-9a2c-4077e461e1f6.png)

**Comment by snap01** [comment]
This appears to be an issue with the FoundryVTT Import Data function as this issue also appears in other systems.

An issue on the FoundryVTT issue tracker has been raised for this.

**Comment by snap01** [comment]
This has been resolved in FoundryVTT 0.8.7
