### ISSUE TITLE
Bug: Luck spend is allowed on luck roll for hard and extreme success

### ISSUE THREAD

**Issue by anthonyronda** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#58]
I teased this report a while ago, sorry it took so long!

![image](https://user-images.githubusercontent.com/1410433/89819125-e374c480-db18-11ea-8896-e3f3efef39ee.png)
In the above screenshot, the button allowing a "luck spend" to reduce the character's Luck roll to the target number has been correctly removed, because a Luck roll doesn't allow a luck spend. However, the hard and extreme success luck spend buttons are still here. This is an error, as no luck spend is allowed at any level of success.

**Comment by anthonyronda** [comment]
Oops, looks like hard/extreme luck spend buttons are now broken in 0.2.2/0.2.3.

Edit: 
![image](https://user-images.githubusercontent.com/1410433/89836471-d36ade00-db34-11ea-9b96-2f8e52154005.png)
The numbers in the original post's screenshot are now gone in the above screenshot.

![image](https://user-images.githubusercontent.com/1410433/89836550-ff865f00-db34-11ea-9798-d93a0b613c1e.png)
"NaN luck spend" is shown after clicking it. It doesn't actually spend any luck. There are no console errors.

**Comment by anthonyronda** [comment]
this is the change I was testing before seeing there was a new release and pulling changes
```javascript
/*check.js*/
//...
		// Can't spend luck on pushed rolls or luck rolls.
		if( !this.pushing && (!this.isAttribute || this.attribute != "lck")){
				...
		}
//...
```
![image](https://user-images.githubusercontent.com/1410433/89843504-e25a8c00-db46-11ea-8795-040084e2b906.png)

In my test, this doesn't appear to break anything. I'll wait to hear back on the other luck spend bug before submitting a PR for this

**Comment by HavlockV** [comment]
Thanks for feedback. This is corrected for luck and san roll.
Will be pushed on the next release

**Comment by HavlockV** [comment]
> 
> 
> Oops, looks like hard/extreme luck spend buttons are now broken in 0.2.2/0.2.3.
> 
> Edit:
> ![image](https://user-images.githubusercontent.com/1410433/89836471-d36ade00-db34-11ea-9b96-2f8e52154005.png)
> The numbers in the original post's screenshot are now gone in the above screenshot.
> 
> ![image](https://user-images.githubusercontent.com/1410433/89836550-ff865f00-db34-11ea-9798-d93a0b613c1e.png)
> "NaN luck spend" is shown after clicking it. It doesn't actually spend any luck. There are no console errors.

I was not able to reproduce this. Could you detail how you got this bug ?

**Comment by anthonyronda** [comment]
> I was not able to reproduce this. Could you detail how you got this bug ?

I'm not able to reproduce today either, sorry about the mix-up. I'm not seeing any issues in 0.2.5. In fact, the Luck roll behavior works beautifully now! Closing this issue
