### ISSUE TITLE
[Suggestion] SAN roll request

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#586]
CTRL+click on SAN open the roll request window where the default are 'check' test for SAN.

My suggestion is: the default might be a 'sanloss' allowing to enter min/max values

**Comment by snap01** [comment]
If you CTRL + ALT click Sanity it defaults to a Sanity Check

Opening the check link creator on CTRL click is to maintain consistency with other link creations.
