### ISSUE TITLE
Ranged attacks and Sanity

### ISSUE THREAD

**Issue by EctoNoodle** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#597]
Hi,

- When I open up a character sheet from the actors directory, clicking the ranged weapon in order to attack doesn't work (yes I have targetted the thing I wanna shoot at). When you open up a character sheet directly from double clicking the token, the ranged attacks work as expected.

- The bout of madness button on the character sheet gives a message saying "The effects datastore is not yet connected". Same goes for the other button beside it "the underlying insanity".

**Comment by snap01** [comment]
Fixes for both these issues are currently in the develop branch, they should be included in the 0.6.1 release.
