### ISSUE TITLE
Is it possible to add the Occupations?

### ISSUE THREAD

**Issue by luizbgomide** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#598]
Since we already have the skill, I think we could also have a list of Occupations without any description text and just the linked skills and credit rating info. As those are usually name of professions, they probably cannot be copyrighted so I guess there is no infringement here.

I could help in making that list. It would be a time saver for many people.

**Comment by petergeneric** [comment]
@marcstraube thank you so much for this, I generated compendiums from your PR and imported them into my game while waiting for the PR to be merged in and it's saved so much work!

**Comment by snap01** [comment]
Unfortunately these can not be added to the base system as they contain copyrighted material
