### ISSUE TITLE
REQUEST - System settings for armour/damage calculation

### ISSUE THREAD

**Issue by sutekh849** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#600]
At present, manually setting HP goes through this function in actor.js:
```async setHealthStatusManually(event) {
		if (event.originalEvent) {
			const healthBefore = parseInt(event.originalEvent.currentTarget.defaultValue);
			const healthAfter = parseInt(event.originalEvent.currentTarget.value);
			let damageTaken;
			healthAfter >= this.hp ? this.setHp(healthAfter) : false;
			healthAfter < 0 ? damageTaken = Math.abs(healthAfter)
				: damageTaken = healthBefore - healthAfter;
			this.render(true);
			return await this.dealDamage(damageTaken);
		}
	}
```
Which I think is a bit counterintuitive, as subtracting the old health from the new and then subtracting the armour value from the result and then applying *that* as damage is, at least to my mind a bit weird and I believe may well have caused others some confusion (c.f. #440?). I have modified my local implementation to read as follows:
 ```
	async setHealthStatusManually(event) {
		if (event.originalEvent) {
			const healthBefore = parseInt(event.originalEvent.currentTarget.defaultValue);
			const healthAfter = parseInt(event.originalEvent.currentTarget.value);
			if(healthAfter < 0){
				const damageTaken = Math.abs(healthAfter);
				this.render(true);
				await this.dealDamage(damageTaken);
			} else {
				await this.dealDamage(healthBefore-healthAfter,{ignoreArmor: true}); 
			}
		}
	}
```
Which I find more intuitive for manually setting actor HP, while retaining the option to use a negative value to apply armour to the damage. I appreciate that the less automated approach might not be best for everyone, so I'd like to suggest a system setting be added to enable switching between the two approaches.

Many thanks for the great system!

**Comment by joaovscorreia** [comment]
Hello, sutekh849. First of all, thanks for your comment! This function was my implementation. I believe that this is not the issue you mentioned (#440), as this is from March, and this piece of code only came to the system in May (#538). I confess that this code was rather confused, hahah. I'm not a programmer, I learned JS to help with the system, just like many here. Admittedly, there was no need for these confused ternary operators! It is possible, yes, to do a refactoring. As for your code, unfortunately I can't test it right now. But I get the impression that it doesn't deal with the possibility of increasing hit points manually. But the part about including the ignoreArmor option makes perfect sense! I hadn't been aware of the fact that armor was being counted. Thanks for the alert! I will do the proper refactoring as soon as possible.

**Comment by sutekh849** [comment]
Happy to help, especially if something feels a bit off as it did in this instance. Congratulations on helping to develop the system despite being new to JS! The ternary operators in that are a bit confusing and should definitely be refactored out in my view.
I can confirm that in my testing I was able to increase as well as decrease HP, presumably due to underlying functions in foundry's character sheet template system - however, if you think it should be explicitly handled in this function, might I propose something along the lines of the following:

```
async setHealthStatusManually(event) {
		if (event.originalEvent) {
			const healthBefore = parseInt(event.originalEvent.currentTarget.defaultValue);
			const healthAfter = parseInt(event.originalEvent.currentTarget.value);
			if(healthAfter > healthBefore) {
				//is healing
				await this.setHp(healthAfter);
			}
			else if(healthAfter < 0) {
				const damageTaken = Math.abs(healthAfter);
				await this.dealDamage(damageTaken);
			} else {
				await this.dealDamage(healthBefore-healthAfter,{ignoreArmor: true});
			}
		}
	}
```

**Comment by castanhocorreia** [comment]
Resolve #605
