### ISSUE TITLE
REQUEST: Dead icon of some kind appears on NPCs when they hit 0 hit points

### ISSUE THREAD

**Issue by ghost** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#607]
I know when I click on an NPC on the battlemap I can see that they're dead, but this doesn't happen when a character shoots an NPC to 0 hp. Not in any little test I've managed. An icon overlay on a token showing an NPC is dead would be handy.

**Comment by joaovscorreia** [comment]
@TinyPirate, this issue has been resolved in the latest system version, 0.6.3. If you have any other suggestions, please let us know!
