### ISSUE TITLE
[BUG] Roll Requests not working anymore

### ISSUE THREAD

**Issue by Carter7777** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#615]
Hello,
Roll Requests are not working anymore.
I used to click on the request Roll Request to add in the chat the roll request.
Then player could click on it to realize their test.
Thanks in advance to fix it. 

Best Regards

**Comment by joaovscorreia** [comment]
Hey, @Carter7777! Can you give more details about how it's not working? I did the tests on the latest version, 0.6.1, and here it is working normally. Thanks!

**Comment by Carter7777** [comment]
Previously by clicking on a code of the Roll Request table, without selecting a character, the test button appears in the chat allowing to a player or all players to click on it to execute their test.
