### ISSUE TITLE
Melee Weapondamage with 0 DB

### ISSUE THREAD

**Issue by mogrogh** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#623]
Unarmed 1d3 + 0 becomes 1d30
Large knife 1d8+0 becomes 1d80 +80 (not sure why it added 80 to that roll)
Wood Axe 1d82 + 0 becomes 1d8+20

Don't know the proper word, treucates or something like that.
![image](https://user-images.githubusercontent.com/69079040/129395697-4793e406-63ee-43d5-9e0a-885dd9b781b0.png)
![image](https://user-images.githubusercontent.com/69079040/129395768-7bc0322c-f751-4b40-8ade-325b7e7e830a.png)
![image](https://user-images.githubusercontent.com/69079040/129395817-3bfb9f47-fe85-41c8-8f87-bfe41bff4979.png)

**Comment by mogrogh** [comment]
![image](https://user-images.githubusercontent.com/69079040/129396189-e05970a5-a799-4fd4-85fb-73a69d14c343.png)

**Comment by mogrogh** [comment]
Also did a test without any modules. Same result.

**Comment by joaovscorreia** [comment]
@mogrogh, thanks for your report! This bug has already been fixed, and its fix will be released in the next update.

**Comment by joaovscorreia** [comment]
@mogrogh, hopefully this issue has been resolved in the latest system version, 0.6.3. If you are still having this problem, please let us know!

**Comment by mogrogh** [comment]
Yes, looks fixed. 0.6.4 tested.
![image](https://user-images.githubusercontent.com/69079040/129839873-a0dcf562-99a8-4bfa-a6f0-53a9115b7b01.png)
