### ISSUE TITLE
[translation] Up-to-date fr.json

### ISSUE THREAD

**Issue by vonv** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#627]
Update of the french translation
[fr.json.txt](https://github.com/HavlockV/CoC7-FoundryVTT/files/6990524/fr.json.txt)

**Comment by vonv** [comment]
Last update :)
[fr.json.txt](https://github.com/HavlockV/CoC7-FoundryVTT/files/6990761/fr.json.txt)

**Comment by joaovscorreia** [comment]
Merged! Merci beaucoup!
