### ISSUE TITLE
Increasing the font size

### ISSUE THREAD

**Issue by Drevarte** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#629]
The font size is very small, especially the skills. It's really hard to read and it's just more comfortable using formfillable pdf rather than the system's character sheet.

**Comment by joaovscorreia** [comment]
You can activate the option Override Sheet Artwork under System Settings:
![image](https://user-images.githubusercontent.com/80350000/129903787-f307c803-1aad-4186-88da-60fe5ebd5a90.png)
Then, you can set the value for Default Font Size as you like:
![image](https://user-images.githubusercontent.com/80350000/129903918-86d38be5-438e-41d1-9eda-fb8c83235dd8.png)
