### ISSUE TITLE
[Enhancement] Combat flow add do nothing to dodge/counterattack options where appropriate

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#636]
Two enhancements:

1. Do not allow to dodge/counterattack if the target is death or unconscious.
2. When someone is attacked allow an action "do nothing", to simulate a target that is not aware of the attack or other circumstance it cannot dodge/counterattack

**Comment by snap01** [comment]
Duplicate of #227
