### ISSUE TITLE
Items Dragged to an NPC Cannot be Edited or Deleted

### ISSUE THREAD

**Issue by Dick-K** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#687]
### Prerequisites.

- [Yes ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Yes] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

If an item is dragged from an actor sheet or the Items tab to an NPC it is then impossible to edit or delete that item on the NPC sheet. No reaction to clicking the edit and delete icons.

## Expected Behavior.

The item should open for local editing on the NPC sheet or be deleted from the NPC sheet.

## Actual Behavior.

There is no reaction to clicking the edit and delete icons.

## Screenshots.

Console errors for attempted edit followed by attempted delete.

![image](https://user-images.githubusercontent.com/73724728/131706515-a9681702-8a78-4605-8d72-7864b575d46c.png)

**Comment by snap01** [comment]
Thanks for the detailed information, this will be resolved in the next release
