### ISSUE TITLE
[Blocking bug] Blocking when launching the game

### ISSUE THREAD

**Issue by keldrilh** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#690]
Right after updating foundry to v0.8.9, I wanted to launch my CoC session and got the message attached. I am in v 0.6.4 on CoC.
I am at your disposal to answer if necessary.

![bug 01092020 - foundry v0 8 9 - CoC v 0 6 4 launching](https://user-images.githubusercontent.com/57942337/131718393-f77bcc6a-707c-4ff5-b519-8db3576ae8a3.jpg)

**Comment by joaovscorreia** [comment]
@keldrilh, which version of the system are you using? Which one was using before update?

**Comment by keldrilh** [comment]
System Foundry : 0.8.9 and 0.8.8 before :)

**Comment by joaovscorreia** [comment]
@keldrilh and the game (Call of Cthulhu) system? Does this warning appear for other new Worlds you create as well?

**Comment by joaovscorreia** [comment]
I'm closing this since we got no answers. If you are still experiencing this problem, let us know!
