### ISSUE TITLE
Roll Types when rolling from NPC and character sheets

### ISSUE THREAD

**Issue by Mcgarnagle1** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#71]
Just used your system for the first session last night and everyone was quite impressed! 

One thing that we did note, however, is that the roll types (ie. Private GM, Blind GM & Self rolls) weren't functioning if we made any rolls directly from the character sheets or NPC sheets (didn't test the creature sheet). All rolls that were made showed up as public even if one of the other options were selected.

**Comment by HavlockV** [comment]
Thank very much for you feedback.
This is a very good point, it's now in the pipe.

**Comment by HavlockV** [comment]
Quick update on this : 
https://github.com/HavlockV/CoC7-FoundryVTT/issues/74#issuecomment-674592607

**Comment by HavlockV** [comment]
Private and blind roll implemented for checks.
To be tested and polished for combat flow

**Comment by HavlockV** [comment]
Private rolls and blind rolls available on 0.2.8
