### ISSUE TITLE
Cannot Unlock or Edit Character Sheets

### ISSUE THREAD

**Issue by RedElmHunter** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#717]
Disabled modules

Generated new world and actors

Acting as GM

**Comment by joaovscorreia** [comment]
Hey, @RedElmHunter. Thanks for the report. We have released a hotfix to fix this issue. Try to update your system version in Foundry. Please confirm it is working as it should

**Comment by RedElmHunter** [comment]
Everything is working as it should be. Thank you and thanks for all the work you put in to integrating CoC for Foundry users!
