### ISSUE TITLE
Dodge and Mother langage not displaying in the character sheet

### ISSUE THREAD

**Issue by vonv** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#754]
### Prerequisites.

- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [ ] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

Dodge and Mother langage not displaying in the character sheet

## Expected Behavior.

**Comment by joaovscorreia** [comment]
Resolved by 0a707aa
