### ISSUE TITLE
Dice So Nice! are not getting rolled when clicking on skill check button in chat card for melee weapon

### ISSUE THREAD

**Issue by tosh823** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#768]
### Prerequisites.

- [X] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [ ] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

I noticed a strange bug with chat cards for weapons. If I have a melee weapon, target a character and click on rolling "Brawl" from the chart card for that weapon, the Dice So Nice! dice are not getting rolled, the roll sound is played, and the result is immediately shown on the chat card.
![Bug1](https://user-images.githubusercontent.com/11402260/132954051-8d497e2f-0671-4b7a-bf06-89d4f5537d2e.PNG)

When I use ranged weapon, and do the same thing, after hitting roll skill button on the chat card, the dice are getting rolled and result is updated on the card after that. 
![Bug2](https://user-images.githubusercontent.com/11402260/132954057-30cd0e35-b3f2-4878-99b5-74b2684de3c4.PNG)
 
## Expected Behavior.

The dice roll should be visible on melee weapons as well.

## Possible Fix.

I have a gut feeling that the fact that melee weapon calls for an opposed roll is guilty in here, but I wasn't able to quickly determine in code where is the actual issue.

**Comment by joaovscorreia** [comment]
Resolved by 0a707aa
