### ISSUE TITLE
Only the first weapon is created when importing a statblock

### ISSUE THREAD

**Issue by farling42** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#769]
Only the first attack is created, and it doesn't have a skill associated with it.
An error is reported in the console.

### Prerequisites.

Foundry VTT 0.8.9
CoC 0.6.7

## Description.

The reported error is aborting the creation of attacks, so subsequent attacks in the stat block are not created.

## Expected Behavior.

Weapon should  be created with associated skills

Only the first weapon in the stat block is created, and it isn't associated with a skill.

## Possible Fix.

I've tracked it down to handleTheAttacks, but I don't quite understand why you need this change:

Original:

```
const createdAttack = await this.setMainAttackSkill(createdAttacks[0], newSkills[0]);
```

Fixed version:
```
const createdAttack = await this.setMainAttackSkill(createdAttacks[0][0], newSkills[0][0]);
```

I've no idea why the createEmbeddedDocuments is returning an array of arrays.

**Comment by pconcepcion** [comment]
This may be related to the fix done on the pull request #755
