### ISSUE TITLE
Visual bug when spending luck

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#95]
![luck](https://user-images.githubusercontent.com/470640/90978735-e378b980-e547-11ea-95a7-35902970944f.png)
When you spend luck to achieve a degree of success the number that is reported as spent is wrong, even though the number that gets deducted from the actor is correct.

**Comment by HavlockV** [comment]
Ok, it is still displaying the old roll result.
I'll have a look at it.

**Comment by HavlockV** [comment]
Fixed in 0.3.1
Luck spent correctly displays on the roll card.
Thanks for your feedback, much appreciated.
