### ISSUE TITLE
HP Bar not appearing on token

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#97]
The HP bar cannot be set properly on the token because it looks like the max HP value is not passed and the bar is not drawn.

![image](https://user-images.githubusercontent.com/470640/90981977-1cbb2480-e55c-11ea-954d-0ea0131144d3.png)

**Comment by HavlockV** [comment]
Thanks for the report, appreciated. I will have a look at it ASAP (busy week at work )

**Comment by HavlockV** [comment]
Bar now appears correctly. Available on develop, will be merge in the next release.

**Comment by HavlockV** [comment]
Fixed on 0.3.3
